### ISSUE TITLE
Dashboard tweaks, Team settings, Responsive layout

### ISSUE THREAD

**Issue by matthewcpaul** [qawolf/qawolf#1102]
### Dashboard tweaks
This is a list to get myself started on documenting UI/UX tweaks. Please continue to add more comments if you notice other things or have feedback!

**Trigger tags and groups**
- [x] Define trigger colors
- [x] Display group(s) as a property on a test
- [x] Trigger icons vs colors (the trigger-type icons only show up in the dialog, but colors don't show up there)

**Dialogs**
- [x] Hide/disable 'Assign to group' if there are no groups, or allow group creation in this flow
- [x] Remove list of tests from 'Assign to group' and 'Delete' actions dialog/confirmation (I think it can just include the number in the dialog title or description)
- [x] Delete test confirmation ("this cannot be undone" in description, and an 'I understand' checkbox)
- [x] Delete group dialog/confirmation ("This will permanently this group, but not the tests inside it"
- [x] Consolidate dialog list, checkbox, & radio designs (groups vs triggers vs environments, confirmations etc.)

**Main views**
- [x] Consolidate heading and list item typography
- [x] Consolidate list visual design patterns—either full width or in container
- [x] Hover/active state for list items
- [x] Back icon button when viewing a run suite (goes back to run history)

**Run history and runs**
- [x] Actions on runs: view/edit test

### Settings page
- [x] Team, Members, and Alerts sections

### Responsive design
We need a first pass at responsive layouts for:
- [x] All tests
- [ ] Run history
- [ ] Run suite
- [ ] Settings
- [ ] Run
- [ ] Menu
- [ ] Various actions and dialogs (hopefully shouldn't need much if any work)

**Comment by matthewcpaul** [comment]
### Trigger tags and groups
@flaurida What do you think about this direction for this group of tweaks?

Trigger icons
- Combining colors and trigger-type icons, so the user can better make the association across different touch points

Test list items
- If a group exists as a property on a test, display it with an icon below the test name
- Change the trigger (and now group) names to smaller font size and Gray/7

Trigger modal
- Adding a short description to the triggers modal
- Re-use the same list design (icon buttons on hover, scroll behavior, etc.) as the environment modal

Assign trigger modal
- Use the more understandable/straightforward checkbox design pattern for assigning triggers, put the test count in the modal title, and include a different mini-description

![image](https://user-images.githubusercontent.com/8001871/109709357-63708380-7b6a-11eb-82aa-5e63a037dfaf.png)

**Comment by matthewcpaul** [comment]
### Trigger label colors
**Figma:** https://www.figma.com/file/foQSeIw7cIrCXUUXa8wEbB/?node-id=1106%3A5231

I started with a total of 12 colors, trying to avoid the red and green that we use for pass/fail.

Introducing 5 new colors—in Figma as the **Label** palette; Reusing some colors from the code palette, warning yellow, and two grays.

**Questions:**
- Do we have any data on the average and maximum number of triggers from our users?
- Are we assigning these randomly now, or do you want/need an order for them?

![image](https://user-images.githubusercontent.com/8001871/109724274-58731e80-7b7d-11eb-8bfa-a6ea04ae78f0.png)

**Comment by jperl** [comment]
On average companies will have 3 triggers, 5 max. I will be shocked when one has 12 triggers.

It assigns them in round robin order. 1st trigger: 1st color....12th trigger: 12th color...13th trigger: 1st color, etc.

So it would be good to have an order.

**Comment by matthewcpaul** [comment]
Creating new environments and groups pattern
I love the UX and interaction details of this feature that shares the same pattern, but:
- There's no way to "cancel". Can we do something like clicking anywhere outside of the input and `esc` key will exit this flow and remove the input field? Or do you have any ideas?
- The only way to successfully "create" is to hit `enter`/`return`. Similarly, if a name is typed, and they remove focus of the input by clicking elsewhere, should it save/be created?

![image](https://user-images.githubusercontent.com/8001871/110016424-00f6bf00-7cf3-11eb-907d-8b2e5ced8d73.png)
![image](https://user-images.githubusercontent.com/8001871/110016460-0c49ea80-7cf3-11eb-8be5-7c5859e0dfff.png)

**Comment by flaurida** [comment]
You are correct, the only way to "cancel" now is by pressing Enter when the input is empty. One option is if they click away/esc with no value, it is cancelled. Otherwise it is saved. Thoughts?

**Comment by matthewcpaul** [comment]
Let's do that!

**Comment by matthewcpaul** [comment]
### Add to group modal
The goal is to make this the same/similar to the 'Assign triggers' modal, except the differences that the radio input introduces—only one can be selected at a time.

Mock 1:
- Single test, doesn't belong to any group
- We could remove the "1 test" from the heading (and do this for triggers too)

Mock 2:
- Single test, belongs to an existing group
- The 'No group' option is now visible

Mock 3:
- Bulk action on 3 tests, belong to different groups (so nothing is selected)
- The 'No group' option is visible because 1 or more of the selected tests currently belong to a group

![image](https://user-images.githubusercontent.com/8001871/110024758-7ca93980-7cfc-11eb-89b2-97a5ec5a1d03.png)

**Comment by matthewcpaul** [comment]
### Delete test(s) modal
I was thinking there could be a more elegant way to handle this:
- Like the other modal changes, include the number in the heading and get rid of the list of tests
- Because it can be 1 or multiple, instead of typing in something, there could be a checkbox with the label "I understand"

![image](https://user-images.githubusercontent.com/8001871/110029033-014a8680-7d02-11eb-8dce-0cb9c5a60276.png)

---

### Delete group modal
- Can we add some additional copy to let users know the tests won't be deleted
- I don't see this destructive action as severe (similar to deleting a single environment variable), and shouldn't need the additional confirmation of typing the group name

![image](https://user-images.githubusercontent.com/8001871/110029247-3525ac00-7d02-11eb-94b4-6daab57183a9.png)

**Comment by matthewcpaul** [comment]
@flaurida What do you think of these adjustment to the dashboard layouts in support of the responsive decisions?

### All tests
3 possible content variations (depending on how you want many breakpoints we want, we can add/remove content and functionality)
- Consistent header across all views
- Consolidate the search and filter(s) + the list header/select all row
- List items full width instead of in a separate container

![image](https://user-images.githubusercontent.com/8001871/110685914-c8505d00-81ac-11eb-822b-3c1db8f48c1a.png)

### Run suite
- Same layout adjustments
- Updated header typography/design
  - I was thinking a back button might be nice here to navigate back to run history
- `...` button could review an 'Edit test' action (maybe not necessary, but just thinking users might want to go straight to the test)

![image](https://user-images.githubusercontent.com/8001871/110686925-f2564f00-81ad-11eb-8de0-ba8135a4a725.png)

### List item/card hover state
I think this would be a nice small addition
- `:hover`: Gray/1
- `:active`: Gray/2

![image](https://user-images.githubusercontent.com/8001871/110687342-642e9880-81ae-11eb-8bfc-e6f9c30a3301.png)

**Comment by jperl** [comment]
Closing this as done

**Comment by flaurida** [comment]
Responsiveness not done yet

**Comment by flaurida** [comment]
Also realized not including group name on test cards in runs yet

**Comment by flaurida** [comment]
Plz don't close until this is complete
