### ISSUE TITLE
Update Vercel integration

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#1113]
Our current integration uses the preview urls from the GitHub deployment event.

However some users want to use the URLs based on the branch names. We tried to reverse engineer those but it is not possible for edge cases and when there are multiple branches / tags.

- Do a direct integration with Vercel API to support this ^
- Include the GitHub status comment we have with Netlify

**Comment by flaurida** [comment]
Note: check which event makes most sense https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request
