### ISSUE TITLE
Allow hardcoding user location

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#1150]
One of our users needs tests to run in the USA.

**Comment by Vac1911** [comment]
Might try the proxy settings in [browser.newContext](https://playwright.dev/docs/api/class-browser/#browsernewcontextoptions). The options for: local, timezoneId, and geolocation, may also be useful.

**Comment by jperl** [comment]
Thanks, those will all work currently with QA Wolf.

We also have encountered a few users now that detect location based on ip which is not possible to spoof.
