### ISSUE TITLE
 page.waitforSelector is not a function at qawolfTest

### ISSUE THREAD

**Issue by sbounmy** [qawolf/qawolf#1198]
Hello,

I am trying to use `waitforSelector` instead of `page.$eval` but had this bug

Best,
PS: are all functions from [playwright](https://playwright.dev/docs/api/class-elementhandle#elementhandlewaitforselectorselector-options) available on qawolf ? 
## Bug description
```js
const { context } = await launch();
const page = await context.newPage();
await page.goto('...', { waitUntil: "domcontentloaded" });

const el = await page.waitforSelector("text=Booker Events");
console.log(el);
```
raises
```log
TypeError: page.waitforSelector is not a function at qawolfTest (vm.js:103:21)
```

**Comment by jperl** [comment]
It is `page.waitForSelector` with a capital `F`.
