### ISSUE TITLE
GitHub comment with test results

### ISSUE THREAD

**Issue by flaurida** [qawolf/qawolf#1209]
## 🐺 QA Wolf - Deployment

🏃 Your tests are running, [see details here](https://www.qawolf.com).

<details>
<summary>❌ 1 fail</summary>
<table>
<tr>
<td>
<div>
<a href="https://www.qawolf.com"><p>❌ Sign up with GitHub</p></a>
<img src="https://qawolf.s3.us-east-2.amazonaws.com/ckmz8z38s000909mlai36h6gb.gif" width="200" />
</div>
</td>
</tr>
</table>
</details>

<details>
<summary>✅ 2 pass</summary>
<table>
<tr>
<td>
<div>
<a href="https://www.qawolf.com"><p>✅ Sign up with email</p></a>
<img src="https://qawolf.s3.us-east-2.amazonaws.com/ckmz8z38s000909mlai36h6gb.gif" width="200" />
</div>
</td>
</tr>
<tr>
<td>
<div>
<a href="https://www.qawolf.com"><p>✅ Log in to existing account</p></a>
<img src="https://qawolf.s3.us-east-2.amazonaws.com/ckmz8z38s000909mlai36h6gb.gif" width="200" />
</div>
</td>
</tr>
</table>
</details>

**Comment by flaurida** [comment]
Note: need to update gifs in AWS to have the correct content type

**Comment by jperl** [comment]
## 🐺 QA Wolf - Deployment

🏃 1 test is running, [see details here](https://www.qawolf.com).

[See details here](https://www.qawolf.com).

<details>
<summary>❌ 1 fail</summary>
<table>
<tr>
<td>
<div>
<a href="https://www.qawolf.com"><p>❌ Sign up with GitHub</p></a>
<img src="https://qawolf.s3.us-east-2.amazonaws.com/ckmz8z38s000909mlai36h6gb.gif" width="200" />
</div>
</td>
</tr>
</table>
</details>

<details>
<summary>✅ 2 pass</summary>
<table>
<tr>
<td>
<div>
<a href="https://www.qawolf.com"><p>✅ Sign up with email</p></a>
<img src="https://qawolf.s3.us-east-2.amazonaws.com/ckmz8z38s000909mlai36h6gb.gif" width="200" />
</div>
</td>
</tr>
<tr>
<td>
<div>
<a href="https://www.qawolf.com"><p>✅ Log in to existing account</p></a>
<img src="https://qawolf.s3.us-east-2.amazonaws.com/ckmz8z38s000909mlai36h6gb.gif" width="200" />
</div>
</td>
</tr>
</table>
</details>
