### ISSUE TITLE
Self-hosted QAWolf installation not working - /api/graphql 500 status

### ISSUE THREAD

**Issue by raidneural** [qawolf/qawolf#1210]
## Bug description

Hi, thank you for the project - it's awesome!

I'm finding issues when installing the QAWolf locally. The problem is, I'm not able to sign up - the endpoint /api/graphql returns a 500 internal server error

## Steps to reproduce

I'm using deno to run develop.ts and following the instructions I'm able to rebuild the docker image and get it up and running. When I visit the app @ port 3000 and try to sign up, I can see a JSON error popping up. Checking the network requests is can be seen that /api/graphql is returning a 500 status with an Internal Server Error message

On the other hand, @ 8787 port I can see how the code for /api/graphql is compiled 'successfully'

Am I missing something?

Thanks again!

**Comment by flaurida** [comment]
Hi @raidneural thanks for the kind words!

Longer term we do want to make self-hosting easier, but for now we are focused on product improvements based on user feedback.

I have a few guesses as to what might be going on but it's hard to say without knowing more about your setup. If you like, we can do a 15-minute call to try to get to the bottom of it: https://calendly.com/qawolf/15min
