### ISSUE TITLE
Better notifications

### ISSUE THREAD

**Issue by flaurida** [qawolf/qawolf#1298]
- Include tag names in notifications for manual/API triggered tests
- Include branch/PR names if possible

**Comment by drumnation** [comment]
Is there a way to display the tests on a PR similarly to how deployments appear? Vs. in the actions part of the PR.

![](https://user-images.githubusercontent.com/18486434/118828599-66d2fb80-b88b-11eb-8b9e-4b00c2a95efb.png)

Would look like a simplified view of the history screen. Showing each row the name of the test run, thumbnail, green/red light, hyperlinks to the history page with the video.  
  
 

![](https://user-images.githubusercontent.com/18486434/118829276-f8426d80-b88b-11eb-8bda-43b3116cc5d6.png)
