### ISSUE TITLE
📅 Allow more schedule configuration

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#1309]
"Every day and every hour is need, I think every week and every month are also need."

Support timezones in front end

**Comment by abenhamdine** [comment]
Hi and first congrats for this promising product !  

Indeed it would be great to be able to schedule more precisely the tests.
For example, we would want to use qa-wolf to test the main features of our production app every morning at 7h am everyday, before our clients start to log in, to ensure the app is properly runnning. 

More generally I think an UI equivalent to a cron scheduling would be appropriate, to handle all use cases.

**Comment by jperl** [comment]
I agree we should have those options. We actually added support for that in our backend but have not updated the UI yet.

If send over chat in the bottom right of QA Wolf the name of the trigger(s) and timezone we can update it to be 7am every morning for you.

**Comment by abenhamdine** [comment]
> Thank you for the feedback @abenhamdine and for the kind words. We actually added support for advanced scheduling in our backend but have not updated the UI yet. If you send over Intercom chat in the bottom right of QA Wolf the name of the trigger(s) and timezone we can update it to be 7am every morning for you from the backend.

It's very kind thx ! We are only exploring the product for the moment, so we are not in a hurry

> I completely agree we should have more options, maybe similar to Google Calendar.

I tought about Google Calendar, but not as rich in terms of recurrence options as a cron expression ui component.

> Our goal is to be the easiest way to set up end-to-end testing, so it's a balancing act between easiness (less options/configuration) and flexibility (more options/configuration). Right now we are planning to add in configuration based on customer needs, and since start time/timezone has come up multiple times we will definitely expose that in our UI at some point.

start time/timezone is definitely needed, no doubt
