### ISSUE TITLE
🧩 Test chrome extension 

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#1310]
Provide an example for testing a chrome extension.

Idea from @pbalmasov

**Comment by jperl** [comment]
Going to MVP this with @davidkaneda

**Comment by davidkaneda** [comment]
Hey Jon — Just double-checking, main goal on my end is still to upload the file (probably zip or CRX) somewhere publicly available and pass the URL to QAWolf via the CLI? It would likely be easier on our end to be able to pass binary data to the CLI, but totally understand if this is tougher on your side-

**Comment by jperl** [comment]
Yes. We could eventually support uploading via CLI, but probably not in the near-term.
