### ISSUE TITLE
2.21.2 cannot build runner

### ISSUE THREAD

**Issue by CalvinMcGee** [qawolf/qawolf#1358]
# Version
2.21.2

# Environment

MacOS 10.15.7  
Docker version 20.10.2, build 2291f61  
docker-compose version 1.27.4, build 40524192

# Bug

```ERROR: Service 'runner' failed to build : COPY failed: file not found in build context or excluded by .dockerignore: stat qawolf.recorder.js: file does not exist```

# Steps to reproduce

On a fresh download of 2.21.2 run `./wolf start`

# Solutions

commit the file `./runner/qawolf.recorder.js`

**Comment by jshimko** [comment]
@CalvinMcGee Try running `./wolf init` first.

**Comment by jshimko** [comment]
Actually, you'll need to run `./wolf build` first since that runner base image is no longer published.  Using `./wolf init` tries to pull that image, but it's no longer there.  I'll submit a fix PR for that shortly.

**Comment by jperl** [comment]
@CalvinMcGee We are re-architecting the project organization and do not have a simple way to run the whole stack as of right now. 

Closing since this is not an immediate priority for us.
