### ISSUE TITLE
Challenge trying to signup via link here

### ISSUE THREAD

**Issue by carehart** [qawolf/qawolf#1362]
Folks, I'm a newcomer to QA Wolf, trying to signup, and having a challenge. I suspect perhaps there's not just a temporary problem but perhaps a change in how things are supposed to work which may not be reflected everywhere. Let me explain, and you can correct me if I am misunderstanding.

First, the readme page here has a "signup" link, yet on getting to [that page link](https://www.qawolf.com/sign-up) and filling in the offered form with my email address and hitting the (only available) button "signup with email", I get a red message above that box saying, "*Please request access to use QA Wolf*".  

I assumed that using this form WAS the way to request access.  What would be the next step? 

I looked to see if there were any other (even closed) issues here discussing this but I find none. 

Second, I happened to notice also that on the qawolf.com site, clicking the "signup" button offered on the top right opens instead just a box, asking for our email address, but the button next to it says "schedule demo". And of course the front page itself starts out with a large banner with a field for an email address and the same "schedule demo" button.

I appreciate that there may be some concierge level of service offered, but is it required? Is there no self-signup process? 

Next, I also saw the [blog post from Jan 2021](https://www.qawolf.com/blog/why-we-open-sourced-everything) announcing that you'd gone open source then, with the implication that there would indeed be a free aspect to use of the tool.  Yet the FAQs at the bottom of that front page also has a "how much does it cost" question, and the answer says "This depends on the size of your team and your QA needs".  So is there a no-cost aspect of using the tool, or is it really "commercial open source"?

Again I really am just trying to connect the dots, as well as report the problem. And really, that is the first and foremost issue I am raising here, how "signup" link offered here on the readme goes to a page where using its form gets the message I reported, which really leaves one stuck. If it's not a new problem, I suspect some folks hitting it might just move on rather than report it, especially if they too felt a little confused about the various things I share above. 

No offense intended. I appreciate it's hard work, running either an open source OR a commercial project. Just trying to help here, in addition to seeking help.

**Comment by jperl** [comment]
Hey @carehart thanks for reaching out. QA Wolf v1 and v2 are open source. You can find them in the version tags from this repo.

The sign up page on qawolf.com is for our service offering which is something separate. We plan to announce more details soon.

**Comment by carehart** [comment]
Ok, but I was asking about the signup link **here**, and about the message I got.

Also, even if you were to remove the link here, there's nothing here or in the docs on the site that discuss installing/implementing the code that IS offered here. Perhaps that's intentional. I just wanted to ask, and to share how it all appears to a first-time visitor.

**Comment by jperl** [comment]
Thanks I appreciate your feedback @carehart. This is definitely something we are aware of and have planned to improve.
