### ISSUE TITLE
[CLI]: Nothing shows up if an unknown command is supplied

### ISSUE THREAD

**Issue by jamesgeorge007** [qawolf/qawolf#139]
`qawolf junkcmd`

### What expected

```bash
Invalid command junkcmd
Usage: index.ts [options] [command]

Options:
  -h, --help           output usage information

Commands:
  record <url> [name]  record a workflow and create a test
  test [name]          run a test
  github               set up a GitHub Action
```

**Comment by jperl** [comment]
Thanks I will fix this!

To Do

- [ ] fix ^ 
- [ ] add unit test (need to start adding unit tests to cli)

**Comment by jamesgeorge007** [comment]
Just shooted a PR #140

**Comment by jperl** [comment]
Thanks a bunch 🙏! I am just going to add a unit test then merge your PR.

**Comment by jperl** [comment]
Actually I will setup unit tests after merging the rest of your PRs :)
