### ISSUE TITLE
💡 assertProperty helper

### ISSUE THREAD

**Issue by flaurida** [qawolf/qawolf#163]
* Right now we have the `findProperty` helper that gets the property of an element when it finds it, timing out if element not found. 
* A nice addition would be `assertProperty`, which waits until the property of an element is a specified value, timing out and failing the test if either the element is not found or the property does not equal what is expected.
* This solves the use case where the specified element is found but the property hasn't changed yet.

**Comment by jperl** [comment]
This can be handled by using the result of findProperty
