### ISSUE TITLE
Improve hasText documentation

### ISSUE THREAD

**Issue by flaurida** [qawolf/qawolf#243]
* `hasText` actually waits until text is visible, rather than returning true or false
* Also, "timeoutMs <?number> maximum time to wait for a page to open. Defaults to 5000." I believe is actually the amount of time to wait for the text to appear before giving up
* An alternative is making `hasText` simply return the boolean, and then add an `assertText` helper that waits for text to appear and then fails if it doesn't before timeout

**Comment by jperl** [comment]
It should also auto retry on page navigate and other puppeteer errors.
