### ISSUE TITLE
Spam via EMail

### ISSUE THREAD

**Issue by dewey** [qawolf/qawolf#247]
I'm not sure where you scraped my email address from but I find it a very sketchy way to promote your open source library.

I just received this Mail that links to this library:

```
Hi Philipp,

We built this free and open source library for consulting clients that generates 🤖Puppeteer scripts and ✅Jest tests.

I wanted to share it with you in case you find it useful. If you have any questions/feedback, or want help setting it up, please let me know 🙏.

Hope you have a great weekend and happy holidays!


Sincerely,
Laura
```

Where did you get it from, where did I opt in?

**Comment by flaurida** [comment]
Hi Philipp,

I apologize you found my email annoying, and am sorry you don’t think the library can be useful.

We want to be helpful and every response so far has been positive except for this one. However, we will not delete this issue so others can comment, as we want to do what’s best for the community.

Thank you for reporting this, and I hope you have a great holiday season.

Sincerely,
Laura

**Comment by jperl** [comment]
I have also only gotten thankful responses when I have shared the library, but this certainly has changed both Laura and my perspectives. Thanks for sharing this feedback.
