### ISSUE TITLE
🙋Need help? Visit our chat

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#264]
If you have a question about QA Wolf we can help you out in our [Slack chat](http://slack.qawolf.com/).

If you've discovered a bug please [open an issue](https://github.com/qawolf/qawolf/issues/new/choose).

If you want to suggest a feature please [start a discussion](https://github.com/qawolf/qawolf/discussions).

Thanks!

**Comment by Olyno** [comment]
What about Discord? It's probably late to ask that, but I'm just curious for the choice. Discord is really easy to manage any project on it, it's really accessible etc... So I'm just asking 😃

**Comment by jperl** [comment]
The reason we decided to go with Gitter instead of Discord is so that we could embed it in our docs and reduce the effort required to get help.

<img width="1920" alt="Screen Shot 2020-04-30 at 10 03 23 PM" src="https://user-images.githubusercontent.com/1136652/80781137-80918b80-8b2e-11ea-87c5-e9eb963fa00c.png">

**Comment by jperl** [comment]
We are re-evaluating this now, since Slack/Discord has a better experience for engaging users than Gitter. Gitter was good for one time questions, but we are switching to Intercom for that so it is less important.

Right now we are planning to use Slack since we and a lot of our friends already use that for work, so it should be less friction to join ours. However we are open to Discord as well. Please post below if you have any strong preferences.
