### ISSUE TITLE
get started documentation

### ISSUE THREAD

**Issue by alhansrisuk** [qawolf/qawolf#284]
noticed a small discrepancy between the docs on [github](https://github.com/qawolf/qawolf) and at [docs.qawolf.com](https://docs.qawolf.com/docs/get_started) for getting started. 

looks like you need `npx` when running `qawolf record`

documentation on the website just has `qawolf record <url> [name]`

**Comment by flaurida** [comment]
Thanks for reporting! I'll push a fix shortly :)
