### ISSUE TITLE
🤵Jenkins CI Integration

### ISSUE THREAD

**Issue by alhansrisuk** [qawolf/qawolf#287]
Any future plans for Jenkins integration?

**Comment by flaurida** [comment]
Yes, we can do that! Will do this one right after #282 and let you know when it's done!

**Comment by jperl** [comment]
https://jenkins.io/doc/tutorials/build-a-node-js-and-react-app-with-npm/

**Comment by jperl** [comment]
To Do

- [ ] Run Jenkins locally with [jenkinsfile-runner](https://github.com/jenkinsci/jenkinsfile-runner)
- [ ] Setup Jenkins file to run qawolf
- [ ] Add `npx qawolf jenkins` command
- [ ] Update docs

**Comment by jperl** [comment]
@alhansrisuk This will make it into the next version of qawolf. In the meantime you can create a Jenkinsfile to run a node server and qawolf like this:

```
pipeline {
    agent {
        docker {
            image 'circleci/node:12.14.0-browsers'
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            environment { 
                // configure tests with environment variables
                // https://docs.qawolf.com/docs/configuration
                QAW_ARTIFACT_PATH = './artifacts'
            }
            steps {
                sh 'rm -rf ./artifacts' // delete old artifacts
                sh 'npm run start & npx wait-on http://localhost:3000'
                sh 'npx qawolf test'
            }
        }
    }
    post {
        always {
            archiveArtifacts(artifacts: 'artifacts/**/*.*', fingerprint: true) 
        }
    }
}
```

**Comment by jperl** [comment]
@alhansrisuk `npx qawolf jenkins` is now released
