### ISSUE TITLE
[Feature Request]: Notify users if they're using an older version of the CLI

### ISSUE THREAD

**Issue by jamesgeorge007** [qawolf/qawolf#302]
[update-notifier](https://www.npmjs.com/package/update-notifier) serves the purpose here. As from the tagline, `Inform users of your package of updates in a non-intrusive way`.

**Comment by jamesgeorge007** [comment]
@jperl @flaurida I would love to shoot a PR if you guys're willing to have it onboard :+1:

**Comment by jperl** [comment]
Yes please!! Thank you very much :)
