### ISSUE TITLE
🔗Connect to electron

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#313]
Should be a way to record after connecting to an existing puppeteer page. Check this works with electron.

https://www.npmjs.com/package/puppeteer-in-electron

**Comment by jperl** [comment]
Relates to https://github.com/microsoft/playwright/issues/584

**Comment by jperl** [comment]
Is now possible, just depends on playwright support https://github.com/microsoft/playwright/issues/584

**Comment by hajnalbendeguz** [comment]
Playwright has support for electron now: https://www.npmjs.com/package/playwright-electron

**Comment by jperl** [comment]
@hajnalbendeguz This may be possible already. I will try it soon.

**Comment by jperl** [comment]
Moved to https://github.com/qawolf/qawolf/discussions/862
