### ISSUE TITLE
👆Support drag & drop / touch move

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#315]
We need to think about how to do this properly. Recording movements is complicated. Maybe hide this behind a flag.

**Comment by roughsoft** [comment]
are there any plan about this ?

**Comment by jperl** [comment]
We need to wait for Playwright to support drag and drop https://github.com/microsoft/playwright/issues/1094

**Comment by roughsoft** [comment]
https://codecept.io/helpers/Playwright/#draganddrop
maybe you can ref its implements

**Comment by roughsoft** [comment]
or ,add this api in QAwolf helper,
qawolf.dragAndDrop('#dragHandle', '#container');

**Comment by roughsoft** [comment]
@jperl @flaurida

**Comment by jperl** [comment]
Thanks @roughsoft for your suggestion. We are going to wait for playwright to have official APIs for it, since it is part of their roadmap and prefer to generate vanilla playwright when possible.

**Comment by jperl** [comment]
Moved to https://github.com/qawolf/qawolf/discussions/864

**Comment by jperl** [comment]
<img width="761" alt="Screen Shot 2021-05-20 at 11 04 18 AM" src="https://user-images.githubusercontent.com/1136652/119027403-217dff00-b95b-11eb-81af-62f2010ce2cf.png">
