### ISSUE TITLE
 Is it possible to record a operation of the input file?

### ISSUE THREAD

**Issue by kanitabe** [qawolf/qawolf#330]
I tried for click input file button and choose a file, and then send it.
But the file exported was the below.
Do I need to modify my code manually?

```javascript
  it('can click "datafile" input', async () => {
    await browser.click(selectors[1]);
  });

  it('can click input', async () => {
    await browser.click(selectors[2]);
  });

 // end
```

**Comment by flaurida** [comment]
Hi @kanitabe, thanks for using qawolf 😊 

For now you will need to modify the code, but we will work on file uploads in a release soon! Will comment later on exact timeline.

Here is an example of code to upload a file - it uses Puppeteer's [elementHandle.uploadFile](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#elementhandleuploadfilefilepaths) method, but note the full [Puppeteer API](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md) is also supported. qawolf's [browser.find](https://docs.qawolf.com/docs/api#browserfindselector-options) method will return a Promise that resolves to the Puppeteer ElementHandle.

```js
  it('can upload file, async () => {
    const uploadElement = await browser.find({ css: '#upload' });
    await uploadElement.uploadFile('path_to_file.txt');
  });
```

If you provide additional context happy to modify the example above.

**Comment by kanitabe** [comment]
Thank you for answering!
Wow, I expect for update.

I have another request. 
When it comes to testing long operations, when you look at the output code, you won't know which operation you wanted. 
I am glad if there is a function that allows you to make a comment (output as a comment in the code) by some operation during recording, it will be easy to find what purpose it was.

**Comment by flaurida** [comment]
HI @kanitabe - great suggestion! We are definitely going to make the recording experience more interactive, and that is a fantastic idea. Will keep you posted ;)

**Comment by flaurida** [comment]
Here is an issue for file upload: #331 
And here is one for the interactive create experience: #127 

Follow those to see progress, will also update you when things are released! Have a great weekend 😊
