### ISSUE TITLE
Visualization of workflow when creating browser test

### ISSUE THREAD

**Issue by isy** [qawolf/qawolf#336]
When creating browser tests, it is helpful to be able to visualize and delete workflows.

**Comment by jperl** [comment]
That's a great idea. In #127 we will change it so the test is created while you are using the browser. That way you can view and edit the code as you are using the site. Would that solve your problem?

**Comment by isy** [comment]
Did not notice the issue #127  😨

That solve my problem.

**Comment by jperl** [comment]
Ok great then I will close this issue. I will let you know as soon as it is ready, and would love any feedback on it when it is ready.
