### ISSUE TITLE
🎭Change to Playwright, support all the browsers

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#350]
https://github.com/microsoft/playwright
https://twitter.com/aslushnikov/status/1220045633282662401

**Comment by Yuyz0112** [comment]
This will be very cool!

When I see playwright, I'm wondering whether I can combine rrweb with it. Now looks like a good timing to check qawolf as out next E2E tooling.

**Comment by jperl** [comment]
I am going to start working on switching qawolf to playwright tomorrow. 

I want to contribute to rrweb too, there is a lot of potential to use it for debugging e2e tests. Hopefully I can get more time to work on that soon 🙏.

**Comment by jperl** [comment]
@Yuyz0112 Are you interested in using qawolf to test rrweb? If so I can help set that up after this is released in 0.9.0.

**Comment by Yuyz0112** [comment]
Sure. Where should I start or if there is a todo list for checking?

**Comment by jperl** [comment]
I will work on a draft PR to add e2e tests to rrweb after this release, and we can start from there. We are reworking our website and documentation after this release as well.
