### ISSUE TITLE
Karabiner causes issues with keystrokes

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#358]
"I'm running on Mac OS Catalina and use Karabiner to change my Keys (I'm too used to the Windows Layout). When playing back the Keystrokes, it seems that the Karabiner changes are not applied and some special characters like @ is not typed."

from @ZlydeTJ

**Comment by jperl** [comment]
@ZlydeTJ I am curious if this is still an issue in 0.12.0?

**Comment by ZlydeTJ** [comment]
This isn't an issue anymore, in 0.12.0, since the keys were removed.

**Comment by jperl** [comment]
Ok great!
