### ISSUE TITLE
🍰Make REPL easy to use

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#371]
- Find should show the elements it found
- Errors should be clear. relates to #372
~~Automatically set selectors~~ Partially done

**Comment by celeryclub** [comment]
Excited to see what happens with this library!
As part of the first bullet point, I think it would be amazing to have some way to list out a few matching selectors (classes, IDs, data attrs) and allow the user to choose the best selector. That's probably a tall order, but it would really go a long way toward making the generated tests be robust and future-proof.

**Comment by jperl** [comment]
Thanks that is a great idea! We will look into it as part of this ticket.

**Comment by flaurida** [comment]
Thanks for the awesome idea @celeryclub 😊 I'd be curious your thoughts on how to integrate this well with the [`QAW_ATTRIBUTE` env variable](https://docs.qawolf.com/docs/api/environment_variables#qaw_attribute) that lets you choose which attributes to use when creating test code. Definitely want to make it easy for users to choose their selectors!

**Comment by celeryclub** [comment]
@flaurida Clearly I hadn't read the docs well enough. ;) That's a very elegant solution to the problem I was describing. With that in mind, my only suggestion here would be to also support regex matching on classes - I'll open a new issue for that. Thanks!

**Comment by flaurida** [comment]
@celeryclub great idea - I'll start working on that tomorrow! Just so I understand, are you thinking that this will allow you to specify a regex for a CSS class (or other attribute) so it only uses that class if it matches a pattern? For example `qa-.*` would match `qa-class` but ignore `random-class`. Want to make sure that I implement something that solves your problem well :)

**Comment by jperl** [comment]
Closing this issue for now since it is too ambiguous. We added regex support for attributes. And the debugging improvements should be part of #372
