### ISSUE TITLE
Cannot find module 'handlebars' in v0.9.0

### ISSUE THREAD

**Issue by kcubero27** [qawolf/qawolf#393]
I have just installed the new version of qawolf which has support for Playwright. However, when trying to generate a test or when trying to run them, an error appears regarding handlebars.

```
$ npx qawolf create http://todomvc.com/examples/react/#/ myTestName
Cannot find module 'handlebars'
Require stack:
- /Users/kcubero/Projects/extranet/get-ui/node_modules/@qawolf/browser/lib/page/createDomArtifacts.js
- /Users/kcubero/Projects/extranet/get-ui/node_modules/@qawolf/browser/lib/context/QAWolfBrowserContext.js
- /Users/kcubero/Projects/extranet/get-ui/node_modules/@qawolf/browser/lib/context/connect.js
- /Users/kcubero/Projects/extranet/get-ui/node_modules/@qawolf/browser/lib/index.js
- /Users/kcubero/Projects/extranet/get-ui/node_modules/qawolf/node_modules/@qawolf/cli/lib/CreateCodeCLI.js
- /Users/kcubero/Projects/extranet/get-ui/node_modules/qawolf/node_modules/@qawolf/cli/lib/index.js
- /Users/kcubero/Projects/extranet/get-ui/node_modules/qawolf/lib/index.js
```

```
$ npx qawolf test
Cannot find module 'handlebars'
Require stack:
- /Users/kcubero/Projects/extranet/get-ui/node_modules/@qawolf/browser/lib/page/createDomArtifacts.js
- /Users/kcubero/Projects/extranet/get-ui/node_modules/@qawolf/browser/lib/context/QAWolfBrowserContext.js
- /Users/kcubero/Projects/extranet/get-ui/node_modules/@qawolf/browser/lib/context/connect.js
- /Users/kcubero/Projects/extranet/get-ui/node_modules/@qawolf/browser/lib/index.js
- /Users/kcubero/Projects/extranet/get-ui/node_modules/qawolf/node_modules/@qawolf/cli/lib/CreateCodeCLI.js
- /Users/kcubero/Projects/extranet/get-ui/node_modules/qawolf/node_modules/@qawolf/cli/lib/index.js
- /Users/kcubero/Projects/extranet/get-ui/node_modules/qawolf/lib/index.js
```

It can be fixed by installing handlebars in the project but I think that this is not the behavior expected. In case it is, we should add something in the documentation so users install it together with qawolf.

**Comment by jperl** [comment]
Thank you for reporting this. This is an odd error because we do [require handlebars](https://github.com/qawolf/qawolf/blob/master/packages/qawolf/package.json#L31). I am investigating now.

**Comment by kcubero27** [comment]
@jperl Let me know if there's something I can do 👍

**Comment by jperl** [comment]
@kcubero27 I tried to reproduce this locally and [on CI](https://circleci.com/gh/qawolf/node-example/31?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) but I was unable to.

A few thins we can try:

- can you please try to upgrade npm: `npm install -g npm@latest`
- then [reinstall node_modules](https://docs.npmjs.com/cli/ci.html) with a clean slate: `npm ci`

**Comment by kcubero27** [comment]
I just tried what you said and it's still failing.

My versions:
Node: 12.13.0
npm: 6.13.7
qawolf: 0.9.0

I'm trying to reproduce it with some mates on different laptops and versions. If I can, I will try to upload an example 👍

**Comment by flaurida** [comment]
Thanks for reporting this @kcubero27 - I'm trying to reproduce it now as well with those versions.

**Comment by flaurida** [comment]
@kcubero27 I tried installing it on a fresh project and the versions above and it worked for me. Will keep investigating though, let me know if you have any more detail about how you installed.

```
version_test $npm -v
6.13.7
version_test $node -v
v12.13.0
```

**Comment by kcubero27** [comment]
Hi, I tried a couple of different laptops and... it's working. I'm not 100% sure but I think that it could have been related to Node maybe? It seems that now it is working... Anyway, I'll close the task.

Thank you a lot for your effort!! 👏🏻

**Comment by jperl** [comment]
Glad to hear you resolved it. 

We changed to using npm peer dependencies to reduce the install size in this past release, so it’s possible that your local cache might have gotten messed up.

Please let us know if you encounter the issue again and we will try to help as best as we can.
