### ISSUE TITLE
🌲 Use attribute on ancestor as selector

### ISSUE THREAD

**Issue by flaurida** [qawolf/qawolf#415]
Create a css selector with the data attribute targeting the descendant target.

Relates to #412

**Comment by jperl** [comment]
- Add ElementEvent.cssSelector? and generate it in the Recorder
- Rename `step.html` -> `step.target`

**Comment by jperl** [comment]
buildCssSelector pseudocode

```
const dataSelector = '[data-qa="search"]';
if (target has data attribute) {
  return dataSelector;
} 

// ancestor has data attribute, build descendant selector for the target

// include target element tag
let descendantSelector = "input";

// if the target is an input one of “radio/checkbox” and has value, include it
// also do the same thing for selects
descendantSelector += '[value="dogs"]';

return `${dataSelector} ${descendantSelector}`;
```

**Comment by jperl** [comment]
I tested everything again after mousedown change https://github.com/qawolf/qawolf/pull/431. Please make these fixes after #431 is merged.

1. When clicking second set of labels for http://localhost:3000/checkbox-inputs (Best pet?) — the target is the label, but the label has a control property which is the input#cat. I checked and radio button target labels also have the right control property. We should handle that (and add tests for both).

<img width="760" alt="Screen Shot 2020-02-21 at 2 40 50 AM" src="https://user-images.githubusercontent.com/1136652/75030690-e5ab6f80-5461-11ea-836a-6b09934df6c2.png">

**Comment by jperl** [comment]
2. 
Trying to click the calendar icon in the material ui date picker http://localhost:3000/date-pickers

Selector [data-qa='material-date-picker'] should be [data-qa='material-date-picker'] button

We should change our descendant logic for click events. The descendant should be the clickableAncestor of the target. (I clicked on a path, but the parent button would have been the clickable ancestor). That way we do not jump above unclickable parts of the tree

```
if (isClick) {
  return ` ${getClickableAncestor(element).tagName.toLowerCase()}`;
}
```

This is the change that should fix it. I tested it manually and it works. Just needs some tests.

**Comment by flaurida** [comment]
Use [RXJS](https://stackoverflow.com/a/48671946/230462) to group nearby `mousedown` and `click` events. Rank the target based on this criteria:
- rank inputs highest (clicking on label triggers click event on input like radio/checkbox)
- deepness in the tree (body vs label)

**Comment by jperl** [comment]
Let's not use observables/RXJS yet for simplicity. When there is more complexity in our event recording we should revisit refactoring.

**Comment by jperl** [comment]
Should not be resolved with https://github.com/qawolf/qawolf/pull/454
