### ISSUE TITLE
⌨️ Do not clear in type by default ⌨️ "type(..., { replace: true})" when entire text value is selected

### ISSUE THREAD

**Issue by flaurida** [qawolf/qawolf#416]
"I usually change the values a bit. If I append the filled textfield it replaces the values." from @ZlydeTJ #412

- Do not clear in `type`, remove `options.skipClear`
- Add `type` `options.replace` which selects all before typing. Therefore replacing the text.
- In create, automatically set `options.replace=true` if user clicks to select all, or cmd+a (mac), or ctrl+a (linux/windows) to select all

**Comment by jperl** [comment]
`isClearSequence`: a sequence of type events, that result in the element being cleared (whereas it was not before hand). these events should be ignored in the build type steps.

This is true for: multiple backspaces, select all and delete, cmd+a delete.

Still need to figure out "select all and type".

**Comment by jperl** [comment]
We could instead do something like `selectRange(selector)` which would be more flexible. However the most common use case is just to clear something. I would prefer my code to be `clear(selector); type(selector, valueWithoutBackspace)`. So that is why I think we should stick with `clear`.

**Comment by jperl** [comment]
We could also do `browser.type(selector, { selectAll: true })` if CMD+A or selection range is all.

**Comment by jperl** [comment]
` { replace: true }` sounds better and is still accurate.\

**Comment by jperl** [comment]
Make sure we have tests for content editable.

**Comment by jperl** [comment]
Make sure to test date inputs

```
Evaluation failed: DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('date') does not support selection.
```

**Comment by jperl** [comment]
Add test typing for date inputs. There is an issue with sendCharacters vs type, we should find out why.
