### ISSUE TITLE
🗑️Allow overwriting existing code in qawolf create

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#440]
Delete a file if it already exists.

**Comment by celeryclub** [comment]
One use case I have is getting the browser to a certain state before beginning recording. So let's say I have a login function. I want to create a new test so I set up a new test file that only calls the login helper, then I want the rest of the test to be generated by recording. Would that use case be covered by this feature?

**Comment by jperl** [comment]
@celeryclub That is a very common use case. Right now you can use the repl to call set up steps, which is not ideal.

Right after the API refactor #432 I am going to add the ability to create more steps on an existing file. #376 #405

**Comment by celeryclub** [comment]
Amazing. Thanks for the info!

**Comment by jperl** [comment]
npx qawolf create will ask if you want to overwrite in the next release
