### ISSUE TITLE
🤝Integration with jest-playwright

### ISSUE THREAD

**Issue by celeryclub** [qawolf/qawolf#444]
It's not quite clear to me how, if at all, this project relates to https://github.com/mmarkelov/jest-playwright. It appears to me that they're completely separate at the moment. Have you considered using jest-playwright under the hood?

Thanks!

**Comment by jperl** [comment]
After https://github.com/qawolf/qawolf/issues/432 it should be feasible. I would need to coordinate with @mmarkelov since there is some overlap.

**Comment by celeryclub** [comment]
That makes sense. FWIW I was able to run my code generated by QAW using jest-playwright, but I wasn't sure if this was a safe/sustainable approach or not.

**Comment by jperl** [comment]
It should be safe, I will make sure it is as part of #432

**Comment by jperl** [comment]
Right now you need to use the qawolf.launch to record the video on CI, since it puts the browser on a separate display.

It also sets up some internal stuff when you do launch for the qawolf helpers. However I will make sure that part is unnecessary in #432.

**Comment by celeryclub** [comment]
Understood. Would it make sense to close this since it seems like this functionality is already tracked?

**Comment by jperl** [comment]
I’ll keep it open because I would like to explore moving some functionality out of qawolf and into jest playwright/plugins.

**Comment by jperl** [comment]
We will be actively investigating using jest-playwright for the next release, which will also generate (as close to as possible) vanilla playwright code. Thank you for suggesting this!

**Comment by jperl** [comment]
@celeryclub One concern we have with the current jest-playwright as it stands, is that it sets up a bunch of globals for the test. So just by reading the code, you would not know where the browser, context, or page come from.

Do you prefer these to be "magically" set up for you, or would you want them created within the test?

**Comment by jperl** [comment]
Ok I think the way we are going to solve this issue and #449 is based on our initial call. We will generate a `.qawolf/templates/test.js` and `.qawolf/templates/script.js` default templates. You can edit those, or create your own.

The default will set up the browser/context, so that jest-playwright is not a requirement. However you can delete those set up lines and use jest-playwright as well.

By default we will not create a new it block per step, so that fail fast is not required. We will make that possible with the custom template though.

**Comment by celeryclub** [comment]
Ah this makes sense. Lots of flexibility that way. I guess the trade-off is that upgrading is more complicated, but I think it makes sense as a path forward. 🙌

**Comment by jperl** [comment]
New game plan sorry for the whiplash. We are not going to have a templates feature for the next version, but just an easy way to create in an existing file. 

So if you want a specific template you can just copy a file and call `await qawolf.create()` where you want the code generated.

**Comment by jperl** [comment]
Resolved in https://github.com/qawolf/qawolf/pull/472
