### ISSUE TITLE
"Element not found" error doesn't say what selector it failed on

### ISSUE THREAD

**Issue by celeryclub** [qawolf/qawolf#448]
<img width="701" alt="Screen Shot 2020-02-22 at 2 26 55 PM" src="https://user-images.githubusercontent.com/750809/75098033-8a6f9f00-557f-11ea-80c0-748c7c0c6f63.png">

Apologies if this is already tracked - I may have missed it. Seems like it would be good to log the failing selector rather than making the user try to figure it out based on context.

Thanks!

**Comment by jperl** [comment]
Thanks yeah definitely we should include that in the thrown error. Relates to #372, but I’ll keep it open until we ship this. 

As a workaround, if you set QAW_LOG_PATH it will log more info, including the selector.

**Comment by jperl** [comment]
This should be resolved now that we are using vanilla playwright selectors.
