### ISSUE TITLE
[Convenience proposal] Rename test

### ISSUE THREAD

**Issue by codex-zaydek** [qawolf/qawolf#452]
Something like `qawolf --rename [from] [to]`. When I experimented with QA Wolf yesterday, I noticed that I couldn’t easily rename a test without breaking it because a test is tied to a selector file as well. This is understandable, but adds some cognitive tension when trying to get things done.

Because I imagine QA Wolf will most likely have multiple files per test going forward, I recommend making a command-line tool to automate renaming tests. It’s less of a big deal now that QAW does not enforce camel casing, but I think it would be a nice touch.

The thing to keep in mind is that this may be simpler said than done: truly renaming a test may require _altering_ the content of a test file as well, for example `import ...`, which is even trickier because it requires some kind of reading/rewriting file contents. So you may want to hold off on this simply because this makes it harder to implement.

**Comment by jperl** [comment]
Sorry for the late response, I think we talked offline. Our goal is to inline as many selectors as possible so that the selector file is unnecessary. Going to close this for now.
