### ISSUE TITLE
QAWolf on Raspberry Pi

### ISSUE THREAD

**Issue by JBDCE** [qawolf/qawolf#481]
Im trying to get software running on a raspberry pi and getting into issues regarding arm7 compatibility.
Is there a workaround to this already?
I would love to contribute to this if someone could help me to get started.

**Comment by jperl** [comment]
Hi that's a cool idea! We are interested in adding connect support and hopefully that will make this possible. #313 I will update you when we add connect support.

**Comment by jperl** [comment]
I would also love to learn more about your use case, if you are open to sharing it!

**Comment by JBDCE** [comment]
Thank you very much for your response! This sounds very helpfull indeed. Me and my colleague are trying to use a couple of Raspberry Pies to run tests on our webpages. QAWolf might be a great alternative to our clumsy selenium tests and so far appears to integrate well into our workflow.

**Comment by gandie** [comment]
Heyho! I am a colleague of @JBDCE . Will try your suggestions on manipulating the `executablePath` in the next week.

As my colleague said, we're building on a continous integration platform for web applications in our company ( @perfact ) . We've been using a Selenium-based toolchain for the past years, but wanted to try other frameworks as well. So i found playwright + qawolf, which has already helped us on improving our navigation which had some ambiguous CSS selectors in it. I can provide a short blog post i wrote for our company blog comparing our Selenium-based toolchain with qawolf. Long story short: I fell in love with qawolf :laughing: . 

Using Rapsys as continous integration worker drones seemed like a good idea to us, as we had a lot of struggle running automated browser tests on virtual machines in a reliable manner. Do you have any experience on this? Ever tried to run qawolf in a virtual machine? Not sure if our problems were Selenium- or webdriver related running on VMs.

**Comment by jperl** [comment]
Hi @gandie glad you like using qawolf, we have a lot of improvements planned so it should only get better :). Our API will be a lot more stable after this upcoming release this week (0.12.0), so I actually recommend holding off on adopting it until then.

If possible, instead of using rasberry pis, I would recommend using a CI provider to run your environment and tests like CircleCI or GitHub Actions.

**Comment by derwerner95** [comment]
Hi @jperl we are currently looking into this again. Could you maybe give me some additional info on how qawolf uses/passes the options.executablePath to Playwright? Our main issue right now is that we have to use our own Firefox ESR and Chromium versions that run on ARM, so we somehow need to pass that.

**Comment by jperl** [comment]
Yes please use `npm i qawolf@0.12.0-beta.2` for now, we will be publishing the final release and docs soon.

After you create a test it will look something like this

```
const qawolf = require('qawolf');
const selectors = require('../selectors/keys.json');
const { TEST_URL } = require('./utils');

let browser;
let page;

beforeAll(async () => {
  browser = await qawolf.launch();
  const context = await browser.newContext();
  await qawolf.register(context);
  page = await context.newPage();
});

afterAll(() => browser.close());

test('fill', async () => {
  await page.goto(`${TEST_URL}text-inputs`);
  await page.click("[data-qa='html-text-input-filled']");
});
```

Just pass the `executablePath` to launch, since those options [are passed](https://github.com/qawolf/playwright-utils/blob/master/src/launch.ts#L67) directly to playwright's launch.

```
  browser = await qawolf.launch({ executablePath: "/path/here" });
```

**Comment by derwerner95** [comment]
Thanks a lot for the detailed answer, will try to implement it and let you know whether it works.

**Comment by derwerner95** [comment]
Did some testing today, apparently all of other playwright browser functions return Type Error : Cannot read X of Undefined if i pass my own browser. Am I missing something obvious?

**Comment by jperl** [comment]
@derwerner95 I have honestly never tried using a custom browser. I am happy to [get on a call](https://gitter.im/qawolf/community) with you to help set it up in CI if you are interested. You could try asking in the [Playwright slack](https://join.slack.com/t/playwright/shared_invite/enQtOTEyMTUxMzgxMjIwLThjMDUxZmIyNTRiMTJjNjIyMzdmZDA3MTQxZWUwZTFjZjQwNGYxZGM5MzRmNzZlMWI5ZWUyOTkzMjE5Njg1NDg) for help with the custom browser 🙏.

**Comment by derwerner95** [comment]
@jperl Thanks for your response and the offer. Right now, we are not planning on using a CI provider.
I will definetly check out the Playwright slack. Will keep you updated!

**Comment by jperl** [comment]
I am going to close this for now, since I do not think there is anything actionable for the QA Wolf project to do. It must first be figured out with Playwright how to run a custom browser.
