### ISSUE TITLE
⚙️Add configuration file

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#515]
Read `qawolf.config.js` for global configs

```js
module.exports = {
  // set QAW_ATTRIBUTE once
  attribute: "id,...",
  // jest --config='{}'
  config: '{}',
  // replace the default create templates with your own
  createScriptTemplate: ({ name, url }) => '',
  createTestTemplate: ({ name, url }) => '',
  // where tests are created
  rootDir: '.qawolf',
  // jest --testTimeout=60000
  testTimeout: 60000,
  // generate .ts files, use ts-node for scripts
  useTypescript: false
}
```

**Comment by jperl** [comment]
Make sure the default timeout in npx qawolf test to be >30s (default Playwright timeout). And allow that to be configurable. Based on error investigation done by @mxschmitt

**Comment by mxschmitt** [comment]
> Make sure the default timeout in npx qawolf test to be >30s (default Playwright timeout). And allow that to be configurable. Based on error investigation done by @mxschmitt

not sure if we can set this via some Jest config or CLI parameter. In my application at work I've fixed it with calling this at the top of the file with `35000`: https://jestjs.io/docs/en/jest-object#jestsettimeouttimeout

**Comment by jperl** [comment]
Yes it can be done with `--testTimeout` which the `--repl` flag automatically sets to like 1 day timeout.

**Comment by jperl** [comment]
Will be shipping this next release.
