### ISSUE TITLE
running qawolf to test a storybook project

### ISSUE THREAD

**Issue by dohomi** [qawolf/qawolf#522]
Hello,

I wanted to check out this project and test my deployed Storybook. But apparently none of the clicks are recognized. Is there anything missing? I checked the test.js file but apparently it doesn't seem to listen to any of my clicks. Is this because Storybook uses iframes in the main body?

Any hint is highly appreaciated!
Thanks

**Comment by jperl** [comment]
@dohomi Yes unfortunately we do not support iframes yet. We will add [iframe support](https://github.com/qawolf/qawolf/issues/279) as soon as Playwright supports [cross-frame selectors](https://github.com/microsoft/playwright/issues/152#issuecomment-592206765).

**Comment by dohomi** [comment]
@jperl thanks that will be amazing. Love the simplicity of this project

**Comment by jperl** [comment]
@dohomi Thanks and we have lots of improvements planned! Please keep opening issues with your recommendations.
