### ISSUE TITLE
Different behaviour in Firefox than in Chromium and Webkit

### ISSUE THREAD

**Issue by trivago-vgarcia** [qawolf/qawolf#545]
We are creating some helpers for our tests, and we have noticed that it works in Chromium and Webkit, but not in Firefox.

This is what we are doing:

**helpers.js**
```
let page;
let browser;

async function initHelper() {
    browser = await qawolf.launch();
    const context = await browser.newContext();
    await qawolf.register(context);
    page = await context.newPage();

    await page.click('a[href="/page/1"]');
}

async function stop() {
    await qawolf.stopVideos();
    await browser.close();
}

async function selectValue() {
    return await page.$eval('select[name="whatever"]', el => el.value);
}
```

**test.js**
```
beforeAll(async () => {
    await initHelper();
});

afterAll(async () => await stop());
```

**Error in Firefox:**
```
TypeError: Cannot read property 'close' of undefined

      3 | async function stop() {
      4 |     await qawolf.stopVideos();
   > 5  |     await browser.close();
        |                  ^
      6 | }
```

Do you have any idea how we can make it work in Firefox? Thanks!

**Comment by jperl** [comment]
Thanks for reporting this, I am investigating it now. What version of playwright and qawolf are you using?

**Comment by jperl** [comment]
In the example above. This function takes a browser as as argument:

```
async function stop(browser) {
  await qawolf.stopVideos();
  await browser.close();
}
```

However it is not passed the browser

```
afterAll(async () => await stop());
```

It should be this instead:

```
afterAll(async () => await stop(browser));
```

**Comment by trivago-vgarcia** [comment]
`What version of playwright and qawolf are you using?`

- "playwright": "0.12.1"
- "qawolf": "0.12.4"

`Please let me know if this fixes it for you.`

Sorry, it is a mistake from my side when I have edited the example. That isn't the cause of the error. I have updated the example.

**Comment by jperl** [comment]
@trivago-vgarcia Can we jump on a call?  It would be easier for me to debug the issue with you sharing your screen. https://calendly.com/jperl/30min?month=2020-04

Otherwise can you please run `DEBUG=playwright-utils*,qawolf* yourcommand` and copy the logs here.

**Comment by jperl** [comment]
I tried to reproduce the issue with your helpers here, but it seems to work on all browsers.

https://github.com/jperl/helper-example
https://github.com/jperl/helper-example/runs/552596233?check_suite_focus=true

That is why I would need to see what exactly your code is doing and figure out if there is an issue with your environment.  You can try to run `npm ci` which will reinstall your `node_modules`.

**Comment by trivago-vgarcia** [comment]
Thanks for the help!
I have found the cause of the error. I had changed the testTimeout to 3000. Rolling it back to 60000, it works.

**Comment by jperl** [comment]
Glad to hear the issue is fixed. I will see if we can improve that error message.
