### ISSUE TITLE
Time-outing a test apparently deletes the related selectors file

### ISSUE THREAD

**Issue by arggh** [qawolf/qawolf#546]
I just fiddled with tests, trying to get sign-in to work. After I executed a test that ended in `await qawolf.create();` and the test timed out after I didn't do anything for a short while, QAWolf deleted the related selectors -file, leading to my next test run to fail with this:

```
Cannot find module './selectors/new-test.json' from 'new-test.test.js'
```

**Comment by arggh** [comment]
Seems that if you use `await qawolf.create();` in your test and decide to discard changes, the selectors -file is also deleted.

**Comment by jperl** [comment]
@flaurida we should come up with a clearer pattern here.

**Comment by flaurida** [comment]
@arggh could you explain your use case a bit more so we can find a solution that solves your problem? For example, were you trying to edit an existing test and wanted to abandon your changes? Or something else? Feel free to e-mail me at laura@qawolf.com if you prefer :)

**Comment by arggh** [comment]
In this case I had a previous test that I was trying to extend via `qawolf.create()`, but 

**a)** decided to discard the changes
**b)** didn't interact with the browser and the test timed out

...in both cases, QAWolf deleted the relevant selector mapping file, rendering the actual test file pretty much useless.

```
Cannot find module './selectors/foo.json' from 'foo.test.js'

      1 | const qawolf = require("qawolf");
    > 2 | const selectors = require("./selectors/foo.json");
```

So this is not about solving any use case, but possibly figuring out a more sensible (and less catastrophic) approach to handling these scenarios (a & b), so that existing tests don't end up broken.

**Comment by jperl** [comment]
We are going to add an `npx qawolf edit` command and I will make sure this is not the case.

**Comment by jperl** [comment]
Resolved this issue in https://github.com/qawolf/qawolf/pull/541/commits/c8b6f994766fe5d999387574dd9ff1d73d7fa669

Before we would remove the selectors file, if the initial selectors file had no selectors. However that is a bad heuristic, for the use case you provided (using qawolf.create() manually). Now we only remove the file when QAW_CREATE=true (when npx qawolf create is used).

This fix will be in the next release.
