### ISSUE TITLE
Feature request: Scaffolding

### ISSUE THREAD

**Issue by arggh** [qawolf/qawolf#547]
Maybe I'm doing things the wrong way, but I immediately wanted to have a way to scaffold tests from my own template.

Solved this with a little bit of bash scripting for now.

**Comment by jperl** [comment]
I will make sure we add a doc for this.

**Comment by jperl** [comment]
This is now possible in `qawolf@0.13.0` with qawolf.config.js `createTemplate`. If you provide a function `npx qawolf create` will use the string returned as it's create template.

https://docs.qawolf.com/docs/configure_qa_wolf#createtemplate
