### ISSUE TITLE
Test timeouts in 60 seconds when trying to add new steps

### ISSUE THREAD

**Issue by arggh** [qawolf/qawolf#548]
When `qawolf.create()` is used to add new steps to a test, the test run times out in 60 seconds unless the flag `--repl` is used in conjunction.

**Comment by jperl** [comment]
Thank you reporting this. We are working on an `npx qawolf edit` command that will extend the timeout. In the meantime you can use `--repl` or `--testTimeout` to extend the timeout.

**Comment by jperl** [comment]
We now have an edit command. Please let me know if that works for you!
