### ISSUE TITLE
Typing to pre-filled input at specific position fails

### ISSUE THREAD

**Issue by arggh** [qawolf/qawolf#549]
Modifying the contents of a pre-filled input fails to get recorded properly.

It seems that the position of the content I clicked, where the cursor is placed, isn't saved as part of the test, meaning any arrow key initiated cursor traversal or content insertion isn't reliable.

**Comment by flaurida** [comment]
Hi @arggh thank you for reporting this, I appreciate your taking the time to do so.

This is related to how Playwright's `click` method works. It clicks the center of the element, so the cursor is in the middle when the typing begins. As a temporary workaround, can you try deleting the previous `click` step before your `type` step and see if that helps?

After we release `edit` mode we will dig into this further and see how we can improve it.

**Comment by nrayburn-tech** [comment]
This isn't the most elegant solution, but it may help until there is a better way.
After clicking the input, set your selection position with setSelectionRange.

```
  await page.click("#login");
  await page.evaluate("document.getElementById('login').setSelectionRange(0, 0);")
```

Some more information here, https://stackoverflow.com/questions/512528/set-keyboard-caret-position-in-html-textbox.

**Comment by flaurida** [comment]
Thank you so much @nrayburn-tech 😊 appreciate the solution! 

You can also skip the click step since that is what sets the cursor in the middle. However, it would depend on where you want the selection position as you indicated, so won't work for all use cases. Your solution should support all the cases 🎉

**Comment by nrayburn-tech** [comment]
I wasn’t entirely sure if the click was needed or not. I didn’t investigate too long, so I wasn’t sure what would happen if you used setSelectionStart without the input being focused first. Either way, hopefully this is just a workaround until Playwright can have a better way to do it.

**Comment by flaurida** [comment]
Appreciate it, and yes it is a great workaround 😊 Have a wonderful weekend!

**Comment by aldeed** [comment]
I think #727 will fix this issue, too.

**Comment by jperl** [comment]
This should be fixed now, and shipped in the latest qawolf. Feel free to reopen if you still experience the issue. Thanks @aldeed for fixing it!
