### ISSUE TITLE
Error: Device = not available in Playwright

### ISSUE THREAD

**Issue by hollligan** [qawolf/qawolf#583]
Hi guys! Thank you for a very simple testing framework!! :)
While researching the functionality I tried [this](https://docs.qawolf.com/docs/emulate_a_device).

steps:
1. npm init
2. npm init qawolf
3. (root-Gitlab CI/CD)
4. npx qawolf create --device = "iPad Mini" https://www.wikipedia.org searchTablet

result:
```
PS F:\Git_repositories\research\qawolf-device> npx qawolf create --device = "iPad Mini" https://www.wikipedia.org searchTablet
(node:80672) UnhandledPromiseRejectionWarning: Error: Device = not available in Playwright
    at Object.exports.buildImports (F:\Git_repositories\research\qawolf-device\node_modules\qawolf\build\build-code\buildTemplate.js:19:15)
    at exports.buildTemplate (F:\Git_repositories\research\qawolf-device\node_modules\qawolf\build\build-code\buildTemplate.js:57:29)
    at F:\Git_repositories\research\qawolf-device\node_modules\qawolf\build\cli\saveTemplate.js:19:24
    at Generator.next (<anonymous>)
    at fulfilled (F:\Git_repositories\research\qawolf-device\node_modules\tslib\tslib.js:110:62)
(node:80672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:80672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.     
PS F:\Git_repositories\research\qawolf-device>
```

**Comment by flaurida** [comment]
Hi @hollligan thanks for the kind words 😊 

I just tried it, and the issue is with the extra space between `device` and `=`. So this command works:

```bash
npx qawolf create --device="iPad Mini" https://www.wikipedia.org searchTablet
```

But this command does not:

```bash
npx qawolf create --device = "iPad Mini" https://www.wikipedia.org searchTablet
```

Please let me know if removing the extra spaces fixes the issue for you!

**Comment by hollligan** [comment]
I tried to delete extra spaces, but the problem remained.
`PS F:\Git_repositories\research\qawolf-device> npx qawolf create --device="iPad Mini" https://www.wikipedia.org searchTablet
(node:8944) UnhandledPromiseRejectionWarning: Error: Device iPad not available in Playwright
    at Object.exports.buildImports (F:\Git_repositories\research\qawolf-device\node_modules\qawolf\build\build-code\buildTemplate.js:19:15)
    at exports.buildTemplate (F:\Git_repositories\research\qawolf-device\node_modules\qawolf\build\build-code\buildTemplate.js:57:29)
    at F:\Git_repositories\research\qawolf-device\node_modules\qawolf\build\cli\saveTemplate.js:19:24
    at Generator.next (<anonymous>)
    at fulfilled (F:\Git_repositories\research\qawolf-device\node_modules\tslib\tslib.js:110:62)
(node:8944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8944) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.      
PS F:\Git_repositories\research\qawolf-device>`

**Comment by flaurida** [comment]
Hi @hollligan thanks for reporting this issue - it is working on my end so let me ask a few more questions:

1. Can you try making sure you have the latest qawolf? Please run `npm init qawolf@latest` to reinitialize with the latest version.
2. What terminal are you using?

**Comment by hollligan** [comment]
1 - npm init qawolf@latest
`Installing dependencies
npm install --save-dev jest@^25.3.0
npm install --save-dev playwright@^0.13.0
npm install --save-dev qawolf@^0.13.4`

2 - Microsoft Windows 10 Enterprise, 10.0.18363 - VSC 1.42.1 - powerShell

**Comment by jperl** [comment]
I am able to reproduce this issue on Windows. I will make a fix for windows. Thanks for reporting it @hollligan.

**Comment by jperl** [comment]
For some reason, powershell treats the space as a separate argument. This command will work:

```
npx qawolf create --device='""iPad Mini""' wikipedia.org searchTablet
```

**Comment by hollligan** [comment]
it works! thanks

**Comment by flaurida** [comment]
Thanks @hollligan for reporting - will update our docs accordingly!
