### ISSUE TITLE
Investigate scroll issue

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#596]
Another problem seem to be the scrolling. Whenever I scroll QAWolf puts the following statement into the code:

  await qawolf.scroll(page, "html", { x: 0, y: 538 });
However this triggers an error:

  ✕ twitter-scroll-test (825ms)

  ● twitter-scroll-test

    could not scroll element html

      at ../node_modules/qawolf/src/utils/page/scroll.ts:50:11
      at fulfilled (../node_modules/tslib/tslib.js:110:62)
Version I used: "qawolf": "^0.13.4",

The test:

const qawolf = require("qawolf");

let browser;
let page;

beforeAll(async () => {
  browser = await qawolf.launch();
  const context = await browser.newContext();
  await qawolf.register(context);
  page = await context.newPage();
});

afterAll(async () => {
  await qawolf.stopVideos();
  await browser.close();
});

test('twitter-scroll-test', async () => {
  await page.goto("http://twitter.com/");
  await qawolf.scroll(page, "html", { x: 0, y: 538 });
});
Currently I'm using a workaround:

  await page.evaluate(function () {
        window.scroll({x: 0, y: 0});
      });
This is suboptimal, since QAWolf puts the qawolf.scoll when recording a test.

**Comment by flaurida** [comment]
Currently unable to reproduce this issue, but will leave open until I get more information from @ZlydeTJ

**Comment by flaurida** [comment]
Sample repo here: https://github.com/flaurida/qawolf-scroll-test/actions/runs/90486051
