### ISSUE TITLE
Getting started with tests

### ISSUE THREAD

**Issue by flaurida** [qawolf/qawolf#598]
Points to cover:
- playbook for how to get started with testing 
- differences between testing locally vs staging vs production
- how to configure tests for different environments

@johngrimsey thank you for the idea! Please feel free to comment if I missed something.

**Comment by StephenKoller** [comment]
This would be very helpful.

I'm currently setting up QAWolf with a Docker container for local dev and Jenkins for CI, but the docs only discuss a non-containerized local dev environment and Github Actions for CI.

**Comment by jperl** [comment]
Thanks for your feedback @StephenKoller. QA Wolf 2.0 is much easier to use with Docker and Jenkins and we will make sure to document that use case clearly.

**Comment by StephenKoller** [comment]
@jperl Hi! I found some references to Jenkins setup in the Gitter chatroom, which led me to find the [node-example ](https://github.com/qawolf/node-example)repo - looks like just what I needed!

**Comment by jperl** [comment]
First version of this is done https://www.qawolf.com/docs/your-testing-strategy
