### ISSUE TITLE
qawolf/playwright-ci:v0.9.0 + playwright 0.18.0 = Failed to launch browser

### ISSUE THREAD

**Issue by hollligan** [qawolf/qawolf#599]
after updating the playwright's version from 15 to 18 I started getting an error:
```
Failed to launch browser: Error: spawn /root/.cache/ms-playwright/chromium-764964/chrome-linux/chrome ENOENT
       at ChildProcess.<anonymous> (node_modules/playwright-core/lib/server/processLauncher.js:56:20)
```

use docker image qawolf/playwright-ci:v0.9.0

**Comment by jperl** [comment]
Thanks for reporting this issue, I will be working to update this for playwright@1.0.0 today.

**Comment by jperl** [comment]
playwright-ci@v1.0.0 should not have this issue

**Comment by hollligan** [comment]
the problem remains.

gitlab ci logs (reduced):
```
...

 Using Docker executor with image qawolf/playwright-ci:v1.0.0 ...
 Pulling docker image qawolf/playwright-ci:v1.0.0 ...
 Using docker image sha256:7cf71a5998596e167e93d79d9cf9396c100bacd1f75758505646639a9097316b for qawolf/playwright-ci:v1.0.0 ...

...

$ npx qawolf test --headless --all-browsers ./__tests__/qawolf
 Test: chromium
 npx jest --config="jest.config.json" --rootDir=./ --testTimeout=60000 ./__tests__/qawolf
 FAIL __tests__/qawolf/01-main-page.test.js
   {E2E}-mainPage
     ✕ {chromium}-open page [http://localhost:3001] (3ms)
     ✕ {chromium}-MOCK backend (1ms)
   ● {E2E}-mainPage › {chromium}-open page [http://localhost:3001]
     Failed to launch browser: Error: spawn /root/.cache/ms-playwright/chromium-764964/chrome-linux/chrome ENOENT
       at ChildProcess.<anonymous> (node_modules/playwright-core/lib/server/processLauncher.js:56:20)
```

**Comment by jperl** [comment]
If you are caching node_modules, you need to disable that. Since the browsers are now stored in `~/.cache` and gitlab does not support caching those since they are outside of the project directory. https://github.com/qawolf/playwright-ci/pull/17

**Comment by jperl** [comment]
I confirmed it worked https://gitlab.com/qawolf/playwright-ci/-/commit/200f1cf290e7901b7e2ed7cc8c620df5c5f55ca3/pipelines?ref=master. We will be updating qawolf shortly, after that you can re-run `npm init qawolf@latest` and it will re-generate the gitlab template.
