### ISSUE TITLE
Persistent Launches

### ISSUE THREAD

**Issue by cupcakearmy** [qawolf/qawolf#601]
Hi,
First of all: Thanks for this incredible project. I've been wishing this for sooooo long

Quick question: How do I persist context?

```
const qawolf = require('qawolf')
const { chromium } = require('playwright')

let context
let page

beforeAll(async () => {
    context = await chromium.launchPersistentContext('./data')
    await qawolf.register(context)
    page = await context.newPage()
})

afterAll(async () => {
    await qawolf.stopVideos()
    await context.close()
})

test('example', async () => {
    await page.goto('https://example.org')
})
```

If I run `QAW_ARTIFACT_PATH=./artifacts yarn qawolf test --headless --detectOpenHandles` it works, but only with the `--detectOpenHandles` flag. Kinda dirty.

There is of course the `qawolf.launch` method but no `qawolf.launchPersistentContext`. Is there a preferred/suggested way to do persistence in qawolf?

Thanks!!!

**Comment by jperl** [comment]
The way we recommend persisting state is to use `qawolf.saveState` and `qawolf.setState`. That way you can use the state in parallel across tests.

https://docs.qawolf.com/docs/api/qawolf/save_state
https://docs.qawolf.com/docs/api/qawolf/set_state

--

I have never used Playwright's launchPersistentContext, however it should work. `launch` does not do anything special, it just chooses the browser based on the `QAW_BROWSER` environment variable. This allows us to change the browser in the test command `npx qawolf test --webkit/--firefox`.

I am not sure why you need to use --detectOpenHandles.

**Comment by cupcakearmy** [comment]
Ah perfect, thanks! I'll try with saveState then.

I don't know.. without `--detectOpenHandles` the test suite will not close, probably beacuse the browser stays open.
