### ISSUE TITLE
CTRL+C killing the qa wolf process leaves Active Chromium process

### ISSUE THREAD

**Issue by uptownhr** [qawolf/qawolf#606]
If you kill the qa wolf process before the test completes or closing the browser instance, the test does stop but the browser stays open. This is not that big of a problem but it's annoying as you are not able to X 'close' the browser. You kill have to use your system process manager to manually kill.

**Comment by jperl** [comment]
I agree that would be nice. I opened an issue in Playwright https://github.com/microsoft/playwright/issues/2261 because I think Playwright would need to implement this. 

If you have suggestions for how QA Wolf could implement it, I can reopen this issue.
