### ISSUE TITLE
[Proposal]: A plugin system for creating events

### ISSUE THREAD

**Issue by vkefallinos** [qawolf/qawolf#636]
I have created a fork of qawolf and built a plugin system on top of it.
Would you mind taking a look?
https://github.com/gen-codes/qauto/tree/master/src/actions

**Comment by jperl** [comment]
This is very interesting, thank you @vkefallinos for putting this proposal together. We could also allow installing third party plugins. @flaurida check this out ^

**Comment by flaurida** [comment]
Hi @vkefallinos thank you so much for taking the time to do this - looks awesome! We are going to take a closer look this weekend and get back to you with proposed next steps. Does that work for you?

**Comment by vkefallinos** [comment]
The concept of having installable plugins I think will make this project amazing. The team I work with is considering using qawolf to help us with e2e tests. The features already provided do not cover our needs so I decided to fork the repo and add hooks in specific places in the code to allow for an all-in-one single-file approach for adding event-to-code-generation functionality. 
So I have added: 
- a host hook that is given the playwright `page` object  
- a page hook that run in the page instance
- a prompt hook that adds commands in the cli
- a reducer that has the reduce logic of the events
- a generate hook that generates the code with the events as an input

Me and some of my colleagues can give dev power to the project to build plugins for our needs. 
Hope we have a nice cooperation with you.

**Comment by flaurida** [comment]
Yes, we are excited about this idea, just need to dig into it a bit more. We will get back to you this weekend about next steps. 

Thanks for putting in the time to put this together - happy Friday 🎉

**Comment by roughsoft** [comment]
Great new!

**Comment by flaurida** [comment]
Hi @vkefallinos just chatted a bit more about this - we are definitely interested in moving QA Wolf to a plugin style architecture. It seems like you and your team are very talented, and having your plugins would make QA Wolf better 🐺 

We don't have a concrete timeline yet, but we will do this as part of a future release. We will let you know when we begin work on this. Hope you're having a great weekend 😊

**Comment by jperl** [comment]
Moved to https://github.com/qawolf/qawolf/discussions/884 since we are tracking new features in discussions now
