### ISSUE TITLE
Update to playwright 1.2

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#661]
Also
- Run tests for third party PRs

**Comment by jperl** [comment]
Set up workflow to run tests for PRs

**Comment by jperl** [comment]
Waiting for a resolution from https://github.com/microsoft/playwright/issues/2540

**Comment by hollligan** [comment]
are there any other problems with the update? [microsoft/playwright#2540](https://github.com/microsoft/playwright/issues/2540) is closed.

**Comment by jperl** [comment]
Not that I am aware of. Just waiting for the next playwright release that includes that fix.
