### ISSUE TITLE
qawolf is using .babelrc of root repository?

### ISSUE THREAD

**Issue by thisguychris** [qawolf/qawolf#666]
I'm not sure if this is intended, but my babelrc is messing up qawolf's test.

```
❯ npx qawolf test
Test: chromium
npx jest --config="node_modules/qawolf/js-jest.config.json" --rootDir=.qawolf --testTimeout=60000

 FAIL  .qawolf/todo.test.js
  ● Test suite failed to run

    Using removed Babel 5 option: .stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
```

I'm using babel 5 on one of the repos I'm trying to add e2e test with it.

.babelrc
```
{
  "stage": 1,
  "loose": ["es6.modules", "es6.classes"],
  "optional": ["es7.asyncFunctions", "es7.decorators"]
}
```

**Comment by thisguychris** [comment]
Hi, @jperl 👋 Thank you for pointing out what `qawolf` is doing under the hood.

Since it is invoking jest with a config file:
`npx jest --config="node_modules/qawolf/js-jest.config.json" --rootDir=.qawolf --testTimeout=60000`

I know that babel supports two configurations, but unfortunately the project I'm adding tests for uses babel 5 which doesn't use babel.config.js.

[Jest docs suggest:](https://jestjs.io/docs/en/getting-started#using-babel)
// jest.config.js
module.exports = {
  transform: {},
};

I tried editing that file to 
```json
{
  "setupFilesAfterEnv": ["qawolf/expect-playwright"],
  "transform": {}
}
```

**And it worked, it doesn't read `.babelrc` anymore.** 🕺 

So I guess I can just use jest directly if that's the case but would love to know your thoughts on this:

**Question**: Is there a reason why it needs to read a `.babelrc` if qawolf is passing its own transform anyway (on TS).

**Comment by jperl** [comment]
Good point. I will add `transform: {}` to the default jest configurations in the next release.

**Comment by thisguychris** [comment]
@jperl I just opened a PR for the fix 👌
