### ISSUE TITLE
bug: back slash in artifacts path stops artifacts for being uploaded?

### ISSUE THREAD

**Issue by thisguychris** [qawolf/qawolf#692]
Hi @jperl 👋

So I was checking the GitHub actions generated by `qawolf` it seems to include a backslash? Not sure if it was intended?
`QAW_ARTIFACT_PATH: $\{{ github.workspace }}/artifacts`

This is the commit I added on a minimum repo to reproduce the error:
https://github.com/thisguychris/qawolf-test/commit/7c176267c36003c787661952b3d4ab680b856fa5#r40042947

I'm getting this error:
![image](https://user-images.githubusercontent.com/532797/85189318-975b8f80-b2e0-11ea-81e8-7217f2690b2d.png)

Related actions here:
https://github.com/thisguychris/qawolf-test/actions/runs/141486130

Removing the backslash does seem to make uploading artifact work again? I've only tried this on Ubuntu 18.04

**Comment by jperl** [comment]
Thank you for reporting this. I removed handlebars, and forgot to remove the escapes.

**Comment by jperl** [comment]
This should be fixed now, if you run `npm init qawolf@latest`.
