### ISSUE TITLE
page.click fails for some text= selectors

### ISSUE THREAD

**Issue by aldeed** [qawolf/qawolf#737]
## Issue
Running a test generated after clicking the header search icon on [https://www.nytimes.com](https://www.nytimes.com) fails with a Playwright error. This happens because `text=SEARCH` is generated as the selector, but no element with `text=SEARCH` ever appears on the page in a way that Playwright can/will click it.

First, let's look at how `text=SEARCH` is derived. That happens [here[](https://github.com/qawolf/qawolf/blob/main/src/web/cues.ts#L117).

And the relevant nytimes.com HTML looks something like this:

```html
<button class="css-fnhm75 ewfai8r0" data-test-id="search-button">
  <span class="css-1dv1kvn">SEARCH</span>
  <svg></svg>
</button>
```

As you can see, the `innerText` is actually from the `span`, which has the following CSS:

```css
border: 0;
-webkit-clip: rect(0 0 0 0);
clip: rect(0 0 0 0);
height: 1px;
margin: -1px;
overflow: hidden;
padding: 0;
position: absolute;
width: 1px;
```

According to MDN, `innerText` "is aware of the rendered appearance of text, while textContent is not." In other words, `innerText` (supposedly) doesn't include hidden text.

So our problem restated is this:

The button span text is effectively hidden by CSS, but in such a way as to fool `innerText` into thinking it isn't hidden. However, it *is* hidden well enough that Playwright can't click it when the test script later runs.

To fix this then, we need a way to ensure at the point of selector creation that a text selector can be found by Playwright. We can't simply check whether the target element is visible because `innerText` is created by smushing together the bodies of all descendant elements. We'd have to check whether each descendant is visible and build our own custom "visible inner text" value.

I thought possibly we could use Playwright's `querySelectorAll` in `buildTextCues` to check whether the `text` selector works. However, when I tried this, it does correctly select the span. The problem isn't with selection but with `page.click`, which does a bunch of extra checks to determine whether the selected element is in the viewport, visible, and clickable. These checks fail, and these checks are not part of the public Playwright API so we can't run them in `buildTextCues` as a safety check.

## Conclusion and workaround

At this point, I don't see much benefit in further investigation. We might need changes on a different level, such as using `text=` more selectively and maybe not using `innerText` to get the value for it.

In the meantime, if you see this issue, changing the generated `page.click` to this as a workaround will work:

```js
await page.dispatchEvent('text=SEARCH', 'click');
```

## Secondary issue
Now, for the specific HTML example above, there is a secondary question: Why didn't it build the selector using the `data-test-id` attribute on the `button`, which to us humans is the logical choice. The true bug here seems to be a human mistake. The other elements use `data-testid`, which QA Wolf is configured to prefer by default, but someone added a hyphen making this `data-test-id`.

It does seem that some significant number of projects in the wild use `data-test-id` with the additional hyphen, so I changed `data-testid` to `/^data-test.*/` in the QA Wolf default attribute list in PR https://github.com/qawolf/qawolf/pull/738. This fixes the specific issue on [https://www.nytimes.com](https://www.nytimes.com).

**Comment by jperl** [comment]
Can we not just add a playwright `isVisible` check alongside where we check the playwright `querySelectorAll` matches the first element? https://github.com/qawolf/qawolf/blob/c23a438954d30f5bf07f13652271ef5189ed3844/src/web/selector.ts#L20

**Comment by aldeed** [comment]
@jperl calling `isVisible` doesn't help because it returns `true`. The Playwright error that is thrown is [here](https://github.com/microsoft/playwright/blob/c51ea0afd16fe7abb4857f3b094a5ce592848463/src/dom.ts#L302), and that's due to a bunch of additional complex viewport calculations [here](https://github.com/microsoft/playwright/blob/c51ea0afd16fe7abb4857f3b094a5ce592848463/src/dom.ts#L237). These are additional checks that `page.click` does, above and beyond `isVisible`. We would need to be able to call or recreate `_clickablePoint` function, as well as code to convert the target to a point.
