### ISSUE TITLE
Support ESM

### ISSUE THREAD

**Issue by umaar** [qawolf/qawolf#782]
It'd be great if you could support ESM. E.g. 

If the generated tests used `import qawolf from "qawolf"` that'd be cool. You can check the package.json, `"type": "module"` which can indicate if the project is ESM friendly.

**Comment by jperl** [comment]
Hi @umaar thanks for the feedback! Right now QA Wolf have support for [typescript](https://docs.qawolf.com/docs/configure_qa_wolf#usetypescript) built in and it will import it that way. If you want ESM in a non-typescript project you can [configure the `createTemplate`](https://docs.qawolf.com/docs/configure_qa_wolf#createtemplate). Let me know if that works for you!

**Comment by jperl** [comment]
For my own reference, this is relevant for when we make the template engine pluginable #296

**Comment by umaar** [comment]
So cool, thanks! FYI I'm doing a browser testing workshop and course, and was thinking to show QA Wolf. ESM (in a non-typescript) project will help since I'm trying to showcase 'modern' parts of node. The createTemplate thing looks like it can help!

**Comment by jperl** [comment]
That’s awesome! Let me know if I can be helpful in any way 🙏

**Comment by jperl** [comment]
A lot has changed in 2.0 so I believe this feature request is not as applicable, however feel free to open a new discussion if you think it is since we are moving new feature requests to discussions.

With 2.0 you can copy the generated code into any project and use ESM as you like.
