### ISSUE TITLE
Confirm storybook works with iframe code gen

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#785]
Relates to #279

**Comment by jperl** [comment]
It seems like the code generation works but playwright fails to interact with some elements in the iframe.

**Comment by jperl** [comment]
@dohomi We shipped iframe support in qawolf@1.3.3 and it works for many storybook elements. If you try it out can you please let me know if it works for you?

**Comment by dohomi** [comment]
@jperl thanks I will give it a go soon! great news

**Comment by dohomi** [comment]
@jperl Storybook integration works very neat so far. The only thing I could not get up and running is changing "addon/Knobs" values. But the interaction inside of the frame worked neat!

**Comment by jperl** [comment]
@dohomi Thanks for checking it out. I will look into the addon/Knobs issue. Do you have the url to a storybook that is not working?

**Comment by jperl** [comment]
Closing this for now, since it seems to support it. Will open new issues with future problems.
