### ISSUE TITLE
Support for shadow DOM

### ISSUE THREAD

**Issue by moonlitknight** [qawolf/qawolf#796]
I've just started playing with qawolf, having got good and excited by the videos. However when I run `qawolf create`, none of my interactions with my page are detected. I've tested against www.google.com and all works fine, so the installation seems correct.

The most likely explanation is that my app is built completely from nested Web Components with shadow DOM.

Does qawolf support shadow DOM, or is there any workaround I can implement? I checked and it seems that Playwright since 0.14 has support for CSS selectors that traverse shadow DOM.

**Comment by JosefJezek** [comment]
@jperl do you have any solution?

**Comment by jperl** [comment]
@JosefJezek We definitely will support this. Unfortunately I don’t have a timeline right now because we have some other cool things in the works.

**Comment by jperl** [comment]
We are moving all feature requests to discussions. Please upvote it here if you want this feature https://github.com/qawolf/qawolf/discussions/885
