### ISSUE TITLE
support the same selector engineering as taiko

### ISSUE THREAD

**Issue by roughsoft** [qawolf/qawolf#797]
in repl mode,if we can support the selector policy thinking browser as blackbox, the user experience will more awesome.
https://github.com/getgauge/taiko#smart-selectors
https://docs.taiko.dev/api/relativeselector/
these feature can improve  the productivity of producting command when user interacting web application in repl mode.

**Comment by jperl** [comment]
I believe proximity selectors are being implemented in playwright@1.8.0
