### ISSUE TITLE
Add position to clicks and dblclicks

### ISSUE THREAD

**Issue by aldeed** [qawolf/qawolf#806]
## Problem

Sometimes, where you click matters. The main example I can think of is that a double click on some text will select that text.

However, right now we only generate something like

```js
await page.dblclick('text="Item 6"');
```

Thus the original action causes "Item" to be selected whereas the test run may or may not.

## Solution

Playwright `page.click` and `page.dblclick` have a [position option](https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=pageclickselector-options) that we can use as long as we can determine the x/y offset of the original recorded click event.

**Comment by jperl** [comment]
Moved to https://github.com/qawolf/qawolf/discussions/881 since we are now tracking new features with discussions.

**Comment by jperl** [comment]
Won't fix for now, until this gets more upvotes.
