### ISSUE TITLE
Support hover action

### ISSUE THREAD

**Issue by ivanlepeskevicius** [qawolf/qawolf#839]
It would be incredible to have a way to support the hover action, in some site certain elements are hidden until you place the mouse over a specific part of the page. And currently, QaWolf doesn't support this, the click action is correctly recorded and clicks the correct element, but when I run the test nothing happens since the button is hidden.

**Comment by jperl** [comment]
@ivanlepeskevicius We will definitely make sure to support this, thanks for your suggestion.

**Comment by jperl** [comment]
Moved to https://github.com/qawolf/qawolf/discussions/878 since we are moving to discussions for new feature requests.

With 2.0 you can now easily add the code to hover and keep recording more actions.

**Comment by jperl** [comment]
You can add a snippet for hover, however I will keep this open because ideally code gen would just work.
