### ISSUE TITLE
Set new default beforeAll / afterAll blocks

### ISSUE THREAD

**Issue by derwerner95** [qawolf/qawolf#845]
Hello,

I want to modify the default beforeAll / afterAll blocks for test creation in my QAWolf installation.
For example, i want to ignore HTTPS Errors by default for development/testing purposes and there will probably be more adding up to that that coming in the future. 

What would be the best way to set that up? Where can I make these Changes?

**Comment by jperl** [comment]
@derwerner95 You can change the custom create template. https://docs.qawolf.com/docs/configure_qa_wolf#createtemplate

So you could do something like this:

`qawolf.config.js`

```
module.exports = {
  createTemplate: ({ name, url }) => {
  const code = `const qawolf = require("qawolf");

let browser;
let context;

beforeAll(async () => {
  browser = await qawolf.launch();
  context = await browser.newContext({ ignoreHTTPSErrors: true });  
  await qawolf.register(context);
});

afterAll(async () => {
  await qawolf.stopVideos();
  await browser.close();
});

test('${name}', async () => {
  await qawolf.create("${url}");
});`;

    return code;
  },
};
```

We are also working on a way to simplify all of this, more on that soon.

**Comment by jperl** [comment]
In 2.0 you can now easily change the test, re-run it and continue to add more steps.
