### ISSUE TITLE
Visual testing

### ISSUE THREAD

**Issue by JosefJezek** [qawolf/qawolf#848]
Could you add support for visual testing?

see on this solutions
- https://codecept.io/visual/#using-resemble-helper
- https://theheadless.dev/posts/basics-taking-screenshots/#use-in-visual-regression-testing

**Comment by flaurida** [comment]
Hi @JosefJezek - thank you for checking out qawolf 🐺 

You can integrate any of the libraries mentioned now, as we generate code that you can extend as you like. You can also edit the create template if, for example, you wanted to import Resemble.js in every test. [See the docs here](https://docs.qawolf.com/docs/configure_qa_wolf#createtemplate) 

We are thinking about how to do this better in the medium term as well, will keep you posted.

**Comment by jperl** [comment]
Moving this to the feature discussion https://github.com/qawolf/qawolf/discussions/875
