### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by hollligan** [qawolf/qawolf#850]
I encountered a memory leak problem in the chromium browser.

**Steps to reproduce:**
1. mkdir test_memory_leak_01
1. cd test_memory_leak_01
1. npm init -y
1. npm init qawolf
1. echo -e "const qawolf = require('qawolf');  \n \
  \n \
async function run() {  \n \
  const browser = await qawolf.launch();  \n \
  const context = await browser.newContext();  \n \
  await qawolf.register(context);  \n \
  // const page = await browser.newPage();  \n \
  const page = await context.newPage();  \n \
  \n \
  for (let i = 0; i < 100; i++) {  \n \
    await page.coverage.startJSCoverage();  \n \
    await page.goto('https://www.example.com/');  \n \
    await page.coverage.stopJSCoverage();  \n \
  }  \n \
  \n \
  browser.close();  \n \
}  \n \
  \n \
run();" > test.js

1. date && node test.js && date
1. check memory:
![image](https://user-images.githubusercontent.com/19423656/97882767-089e5b00-1d35-11eb-9f85-432c9083bae6.png)

**environment:**
1. Windows 10 Pro, build 18363
1. node -v -> v12.18.2

**quick fix:**
1. replace "const page = await context.newPage();" to "const page = await browser.newPage();"

**retry test Playwright without qawolf:**

1. mkdir test_memory_leak_02
1. cd test_memory_leak_02
1. npm init -y
1. npm i playwright@1.4.1
1. echo -e "const playwright = require('playwright'); \n \
\n \
async function run() { \n \
  const browser = await playwright.chromium.launch(); \n \
  const context = await browser.newContext();  \n \
  // const page = await browser.newPage(); \n \
  const page = await context.newPage(); \n \
 \n \
  for (let i = 0; i < 100; i++) { \n \
    await page.coverage.startJSCoverage(); \n \
    await page.goto('https://www.example.com/'); \n \
    await page.coverage.stopJSCoverage(); \n \
  } \n \
 \n \
  browser.close(); \n \
} \n \
 \n \
run();" > test.js
1. date && node test.js && date
1. not memory leak! :)

**Comment by jperl** [comment]
Thank you for reporting, we will investigate.

**Comment by jperl** [comment]
Closing this should be resolved in 2.0
