### ISSUE TITLE
CI Question

### ISSUE THREAD

**Issue by spences10** [qawolf/qawolf#855]
Hi, thanks for this, I have a CI question

I work on a team where we deploy to Vercel then use the [`wait-for-vercel-action`] and use that in conjunction with the `CYPRESS_BASE_URL: ${{ steps.wait-for-vercel.outputs.url }}` in a GitHub workflow to test against the pushed branch.

Is it possible to do this with QA Wolf?

[`wait-for-vercel-action`]: https://github.com/mskelton/wait-for-vercel-action

**Comment by jperl** [comment]
You could pass that through as an environment variable to your tests. We are working on a much simpler way to do this though.

**Comment by spences10** [comment]
Thanks @jperl I'll take a look at the environment variables tomorrow 👍 

I'll let you know how I get on

**Comment by spences10** [comment]
I'm happy to close @jperl I couldn't work out how to pass env vars

**Comment by jperl** [comment]
@spences10 We shipped a direct integration with GitHub deployments for 2.0 which we use ourselves to test our Vercel deployments. Happy to help set it up with you. https://calendly.com/jperl/30min

**Comment by spences10** [comment]
Awesome!

Thanks @jperl I've put some time in your Calendly 👍
