### ISSUE TITLE
Video options then saving artifacts

### ISSUE THREAD

**Issue by pbalmasov** [qawolf/qawolf#857]
## Feature Description
Add support of video options

## Why It Is Needed
Can be helpful to reduce file size with reducing fps

## Possible Implementation
Just pass props to saveVideo method from [playwright-video](https://github.com/qawolf/playwright-video#playwright-videosavevideopage-savepath-options)

## Information About Your System

- Operating system: Windows
- Operating system version: 10
- Docker version (if applicable):
- Playwright version: 1.6.2
- Your browser name and browser version: Chrome 87.0.4280.88 (Official Build) (64-bit)
- Browser and version your tests are running in (if applicable): Chromium

**Comment by jperl** [comment]
Hi @pbalmasov thanks for your request.

We restructured the way videos are recorded in 2.0, along with everything else. 

If you still want this feature do you mind opening it under https://github.com/qawolf/qawolf/discussions that is where we are tracking feature requests going forward.
