### ISSUE TITLE
Not working on macOS 11.1 (Big Sur update)

### ISSUE THREAD

**Issue by mariuslundgard** [qawolf/qawolf#866]
## Issue Description

The dependency on `playwright@1.6.2` does not work on macOS 11.1.

### What version of QA Wolf are you using?
v1.6.0

### Errors

```
  ● Test suite failed to run

    TypeError: Cannot read property 'close' of undefined

      13 | afterAll(async () => {
      14 |   await qawolf.stopVideos()
    > 15 |   await browser.close()
         |                 ^
      16 | })
```

### Steps to Reproduce

1. `qawolf test --headless`

## Possible Solution

Upgrade to `playwright@1.7.0`.

## Information About Your System

- Operating system: macOS
- Operating system version: 11.1
- Playwright version: 1.6.2

**Comment by jperl** [comment]
qawolf@1.7.0 is released. Let me know if that fixes your issue

**Comment by aidan-lefrancois** [comment]
This is still occuring with qawolf@1.7.0 and macOS Big Sur v.11.4. 

Steps to reproduce: 
`npx qawolf create url testName`


Error:
● Test suite failed to run

    TypeError: Cannot read property 'close' of undefined

      12 | afterAll(async () => {
      13 |   await qawolf.stopVideos();
    > 14 |   await browser.close();
         |                 ^
      15 | });
`
