### ISSUE TITLE
Playwright not updated for mac11.1

### ISSUE THREAD

**Issue by sdan** [qawolf/qawolf#870]
## Issue Description
When using `qawolf` under `devDependencies` I run into problems with playwright (an underlying dependency it seems). Would appreciate if you could support version 1.7.0.

### What version of QA Wolf are you using?
Using the latest version

### Errors
Can't run QAWolf on Mac11.1. Related: https://github.com/microsoft/playwright/issues/4775

## Possible Solution
Appreciate if you could bump `playwright` to `1.7.0`

## Information About Your System

Mac11.1

**Comment by flaurida** [comment]
Just tried this out on macOS 11.1 and it worked with latest qawolf (`1.7.0`). Please let us know if you are still having issues after upgrading to the latest qawolf.
