### ISSUE TITLE
Documentation missing from qawolf.com

### ISSUE THREAD

**Issue by marcelkooi** [qawolf/qawolf#871]
## Description

There used to be lots of documentation on qawolf.com that does not seem to be there anymore. Did it get moved to somewhere else? Or should we just refer to the `docs` directory in the repo?

There are references in the [readme](https://github.com/qawolf/qawolf#%EF%B8%8F-install) to documentation on qawolf.com. These links point to URLs such as https://docs.qawolf.com/docs/install but are instead redirected to https://www.qawolf.com/docs/what-is-qa-wolf, which doesn't cover installation instructions.

## Links

The "Documentation" links on the readme.

**Comment by flaurida** [comment]
Hi @marcelkooi thanks we are working on this - I sent you an email asking for a few more details to better assist 👍

**Comment by jperl** [comment]
Hi @marcelkooi we are in the middle of a transition to [qawolf 2.0](https://github.com/qawolf/qawolf/issues/865) which is what the new docs points to. You can find 1.0 docs [here](https://v1-docs.qawolf.com/docs/install).

**Comment by marcelkooi** [comment]
Appreciate the quick response! The 1.0 docs are what I was looking for.

**Comment by flaurida** [comment]
Great, closing this issue. Feel free to reopen if you can't find the docs you are looking for.
