### ISSUE TITLE
Lazy initialized frame

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#886]
There are some errors with iframes where the frame gets detached either initially or on a later step on that frame. We should create our own frame helper that lazily gets the frame each method call and gracefully handles detachment.

Ideally this API would be part of [Playwright](https://github.com/microsoft/playwright/issues/3540) but we should implement it in the meantime since it is causing a lot of flakiness for tests with iframes.

`await frame(page, selector)` -> has methods { click, type, etc } that each call ` await (await page.waitForSelector('[class*="-overlay-iframe"]')).contentFrame();` every time w/ retry if it gets certain errors like detached.

<img width="699" alt="1" src="https://user-images.githubusercontent.com/1136652/104509238-9eacf800-55a6-11eb-8150-23578a0a3345.png">
<img width="662" alt="2" src="https://user-images.githubusercontent.com/1136652/104509240-9f458e80-55a6-11eb-9db3-7f281929d78a.png">

**Comment by flaurida** [comment]
We upgraded Playwright and haven't seen again yet. Putting on ice until the issue reappears

**Comment by jperl** [comment]
Closing for now until we see it happen again
