### ISSUE TITLE
chinese bug

### ISSUE THREAD

**Issue by chenshuichao** [qawolf/qawolf#894]
<img width="731" alt="Screen Shot 2021-01-14 at 6 45 48 PM" src="https://user-images.githubusercontent.com/77186544/104580918-d3997780-5698-11eb-882e-274533b2010c.png">
## Bug description

_Describe the issue, including screenshots where helpful._

## Steps to reproduce
const { context } = await launch();
const page = await context.newPage();
await page.goto('https://etax.guangdong.chinatax.gov.cn', { waitUntil: "domcontentloaded" });

**Comment by jperl** [comment]
Seems we are missing some fonts, I will fix this today. Thanks for reporting it!

**Comment by jperl** [comment]
This should be fixed @chenshuichao 
![Uploading Screen Shot 2021-01-14 at 9.36.52 PM.png…]()
