### ISSUE TITLE
Support colon on URL

### ISSUE THREAD

**Issue by hmaesta** [qawolf/qawolf#901]
## Bug description

![Screen Shot 2021-01-14 at 14 23 17](https://user-images.githubusercontent.com/741969/104632437-74c60500-567c-11eb-9037-b0e1adf22073.png)

Colon `:` is a [safe character for URL,](https://stackoverflow.com/questions/2053132/is-a-colon-safe-for-friendly-url-use) but QA Wolf doesn't accept it.

## Steps to reproduce

1. Click "Create test"
2. On modal window, type `http://en.wikipedia.org/wiki/Template:Welcome`
3. Submit

**Comment by flaurida** [comment]
@hmaesta fix should be up soon, thanks for reporting! Also, I sent you an email per our conversation :)
