### ISSUE TITLE
Browser doesn't connect sometimes

### ISSUE THREAD

**Issue by flaurida** [qawolf/qawolf#912]
## Bug description

Browser: Brave (ad blockers off, MacOS)

Infinite loading spinner. Apparently refresh does not work but a new tab did. Screenshots below

![image (5)](https://user-images.githubusercontent.com/6321017/104787474-db1a5880-574c-11eb-971a-03e83d18640a.png)
![image (4)](https://user-images.githubusercontent.com/6321017/104787485-dd7cb280-574c-11eb-99bb-eafeb8a9c7bd.png)

## Steps to reproduce

Run test, ignore it for some time, try to run again

**Comment by jperl** [comment]
This has been drastically improved. Still on the lookout for client errors.

**Comment by jperl** [comment]
This seems to be mostly fixed. Will reopen with new reports.
