### ISSUE TITLE
image can not show correct

### ISSUE THREAD

**Issue by chenshuichao** [qawolf/qawolf#976]
## Bug description
the site in chrome is ok
when I create the test goto the URL,the image can not show 

## Steps to reproduce

https://etax.chongqing.chinatax.gov.cn

**Comment by jperl** [comment]
Thanks @chenshuichao for reporting this. It looks like this site is blocking our servers, so there is nothing we can do about that. You could use the local runner as a workaround. https://www.qawolf.com/docs/test-localhost

QA Wolf is for testing sites you have authorization to test, but not for automating or scraping sites that you do not control. If you control this site, I recommend giving the test access to it via a cookie or token.
