### ISSUE TITLE
Not working on macOS 11.2 (Big Sur update) 

### ISSUE THREAD

**Issue by diogopaulino** [qawolf/qawolf#992]
## Bug description

Can't run QAWolf on Mac11.2.

```js
afterAll(async () => {
  await qawolf.stopVideos();
  await browser.close(); // error here at .close()
});
```

<img width="438" alt="Screen Shot 2021-02-04 at 14 41 53" src="https://user-images.githubusercontent.com/1030809/106940097-e1727380-66ff-11eb-9069-79d8e37e1515.png">

A similar problem happened here too:
https://github.com/qawolf/qawolf/issues/870

**Possible Solution**
Appreciate if you could bump playwright to 1.8.0
https://github.com/microsoft/playwright/releases/tag/v1.8.0

**Comment by jperl** [comment]
Have you tried QA Wolf 2.0? 

It supports [localhost test creation](https://www.qawolf.com/docs/test-localhost) and avoids these environment issues with docker.
