### ISSUE TITLE
Editor v2.1

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#996]
Follow up to #960

- ~Enter a URL to create a test (replace current popup)~ Shipped
- Make the distinction between a run and test more clear
- State before running a test (currently it's "Press the Run button to run your test")
    - Idea: random explanation of a feature with link to the relevant doc
        - Examples: environment variables, assertions
- What should deleted test state be?
- Cancel a run in progress
- Arrow to dashboard - is it clear / prominent enough?
    - Torn because it is very clean and simple
    - Could also explain in onboarding / docs
- Nice to haves
    - Improve editor color pallet together
    - (Likely no design work) Include "run env variables" like `URL` if editing test
        - One idea: store run specific env variables in database
        - If they view run and click to edit test, we include the run variables in the `useEnv` hook (could store `last_viewed_run_id` in local storage)

**Comment by jperl** [comment]
Another use case to consider for the create state:

I often just want to copy the code from another test. Right now the modal blocks me from doing that.

**Comment by matthewcpaul** [comment]
> I often just want to copy the code from another test and press Run

@jperl Do you think this could be solved with a 'Duplicate Test' action?
![image](https://user-images.githubusercontent.com/8001871/107266451-8a2c1600-6a13-11eb-8902-35d4199c3f26.png)

**Comment by jperl** [comment]
> Do you think this could be solved with a 'Duplicate Test' action?

Yes and it probably makes sense to do on the dashboard even more so than here. So you can ignore my last comment.

**Comment by matthewcpaul** [comment]
### Loading state
@flaurida Let's use the new "sitting Spirit" illustration, and animate the tail
- 🎨 [Figma mockup](https://www.figma.com/file/foQSeIw7cIrCXUUXa8wEbB/App?node-id=637%3A2392)
- 🎨 [Illustration (2 states)](https://www.figma.com/file/kDDAsnrv79JLIDwh9uhrCg/Brand?node-id=1%3A16)

![image](https://user-images.githubusercontent.com/8001871/107271328-12adb500-6a1a-11eb-9088-4a8451624d74.png)

![loading-animation](https://user-images.githubusercontent.com/8001871/107269827-26581c00-6a18-11eb-9557-7328ec9557ae.gif)

**Comment by matthewcpaul** [comment]
### Cancel a run in progress
When a Test is running in the editor, the 'Run test' button becomes 'Stop running'

**Questions:**
- What happens to the browser when a Test is stopped? Does it remain at the current step in the test flow?
- What happens to the Pass/Fail icons (the ones that have displayed thus far)?

![image](https://user-images.githubusercontent.com/8001871/107272815-3f62cc00-6a1c-11eb-938c-7702abf056e4.png)

**Comment by matthewcpaul** [comment]
### Make the distinction between a run and test more clear
@flaurida and I had some back-and-forth in Slack about this design and landed on these details:
- The abridged timestamp (23h ago) will display next to the non-editable title
- A dedicated component/row for the metadata, which could include more data in the future, like which browser
- The ‘Run History’ button stays, and the primary header action becomes ‘Edit Test’
- An additional 'Edit Test' button at the bottom of the editor (unsure if it's needed, but we can ship with it for now)
- Grayscale editor theme to further reinforce that it's read-only, and to help place the user's attention on which line failed (if any)
- No "video header" b/c it doesn't serve any function or purpose

![test-vs-run-v2](https://user-images.githubusercontent.com/8001871/107431214-20376d80-6af4-11eb-9647-6cd7404d2c07.gif)

**Comment by jperl** [comment]
Great update. I like it but let's skip the additional edit button at the bottom -- since I think it is confusing to have two ways to do the same thing.

**Comment by jperl** [comment]
I think the only thing remaining is wolf colors

**Comment by flaurida** [comment]
Noting we should change the stop test button colors as well
